/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_randelshofer_quaqua_osx_Application */

#ifndef _Included_ch_randelshofer_quaqua_osx_Application
#define _Included_ch_randelshofer_quaqua_osx_Application
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_randelshofer_quaqua_osx_Application
 * Method:    jniRequestUserAttention
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ch_randelshofer_quaqua_osx_Application_jniRequestUserAttention
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ch_randelshofer_quaqua_osx_Application
 * Method:    jniGetIconImage
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_randelshofer_quaqua_osx_Application_jniGetIconImage
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
