/*
 * AltaUnidades.java
 *
 * Created on 18 de diciembre de 2007, 19:59
 */

package expensav20.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.event.ListDataListener;
import model.Consorcio;
import model.Unidad;

/**
 *
 * @author  Javier
 */
public class AltaUnidades extends javax.swing.JFrame {
    
    private Unidad unidadUpdated=new Unidad();
    private ConsultaUnidad cu=new ConsultaUnidad();
    
    /** Creates new form AltaUnidades */
    public AltaUnidades() {
        initComponents();
        Consorcio cons=new Consorcio();
        this.jCmb_Consorcio.setModel(new ComboConsorciosModel());
        this.jCmb_Consorcio.setEditable(true);
        this.jCmb_Consorcio.updateUI();
    }
    
     public AltaUnidades(Unidad uni,ConsultaUnidad cu) {
        initComponents();
        Consorcio cons=new Consorcio();
        this.jCmb_Consorcio.setModel(new ComboConsorciosModel());
        this.jCmb_Consorcio.setEditable(true);
        this.jCmb_Consorcio.updateUI();
        this.setUnidadUpdated(uni);
        this.setCu(cu);
        if (this.getUnidadUpdated()!=null)
        {
            int index=this.buscarUnidadCombo(this.getUnidadUpdated());
            this.jCmb_Consorcio.setSelectedIndex(index);
            this.jTxt_descripcion.setText(this.getUnidadUpdated().getDescripcion());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCmb_Consorcio = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTxt_descripcion = new javax.swing.JTextField();
        jBtn_Aceptar = new javax.swing.JButton();
        jBtn_Cancelar = new javax.swing.JButton();
        jBtn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de Unidades");
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidades"));
        jLabel1.setText("Consorcio:");

        jCmb_Consorcio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCmb_Consorcio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCmb_ConsorcioMouseClicked(evt);
            }
        });
        jCmb_Consorcio.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_ConsorcioPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_ConsorcioPopupMenuWillBecomeVisible(evt);
            }
        });
        jCmb_Consorcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_ConsorcioActionPerformed(evt);
            }
        });
        jCmb_Consorcio.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jCmb_ConsorcioInputMethodTextChanged(evt);
            }
        });
        jCmb_Consorcio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmb_ConsorcioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCmb_ConsorcioKeyTyped(evt);
            }
        });

        jLabel2.setText("Descripcion:");

        jTxt_descripcion.setColumns(30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCmb_Consorcio, 0, 284, Short.MAX_VALUE)
                    .addComponent(jTxt_descripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCmb_Consorcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jBtn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/tick.png")));
        jBtn_Aceptar.setText("Aceptar");
        jBtn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AceptarActionPerformed(evt);
            }
        });

        jBtn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/cross.png")));
        jBtn_Cancelar.setText("Cancelar");
        jBtn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CancelarActionPerformed(evt);
            }
        });

        jBtn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/door_out.png")));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtn_Aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Salir))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Salir)
                    .addComponent(jBtn_Cancelar)
                    .addComponent(jBtn_Aceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmb_ConsorcioPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioPopupMenuWillBecomeInvisible
        
    }//GEN-LAST:event_jCmb_ConsorcioPopupMenuWillBecomeInvisible

    private void jBtn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CancelarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_jBtn_CancelarActionPerformed
    
    private void jBtn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AceptarActionPerformed
        if (this.validateFields()==false)
            return;
        Unidad uni=new Unidad();
        Consorcio cons=new Consorcio();
        cons=(Consorcio)((ComboConsorciosModel)this.jCmb_Consorcio.getModel()).getLst().get(this.jCmb_Consorcio.getSelectedIndex());
        uni.setDescripcion(this.jTxt_descripcion.getText());
        uni.setConsorcio(cons);
        if (this.getUnidadUpdated().getCodigo()==0)
        {
            uni.guardar();
            if (uni.getCodigo()!=0){
                JOptionPane.showMessageDialog(null,"La unidad se guardó correctamente");
                this.limpiar();
            }
            else{
                JOptionPane.showMessageDialog(null,"Ocurrió un problema, intente nuevamente por favor");
            }
        }
        else{
            uni.setCodigo(this.getUnidadUpdated().getCodigo());
            if (uni.modificar()!=0){
                JOptionPane.showMessageDialog(this.getContentPane(),"La unidad se modificó correctamente");
                this.getCu().actualizar();
          
            }
            else{
                JOptionPane.showMessageDialog(this.getContentPane(),"Ocurrió un problema al modificar la unidad, por favor intente nuevamente");
            }
        }
    }//GEN-LAST:event_jBtn_AceptarActionPerformed

    private void jCmb_ConsorcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioActionPerformed
        ((JTextField)this.jCmb_Consorcio.getEditor().getEditorComponent()).setText(((String)this.jCmb_Consorcio.getSelectedItem()));        
    }//GEN-LAST:event_jCmb_ConsorcioActionPerformed

    private void jCmb_ConsorcioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioMouseClicked
// TODO: Agrege su codigo aqui:
    }//GEN-LAST:event_jCmb_ConsorcioMouseClicked

    private void jCmb_ConsorcioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioKeyTyped
    }//GEN-LAST:event_jCmb_ConsorcioKeyTyped

    private void jCmb_ConsorcioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioInputMethodTextChanged

    }//GEN-LAST:event_jCmb_ConsorcioInputMethodTextChanged

    private void jCmb_ConsorcioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioKeyPressed

    }//GEN-LAST:event_jCmb_ConsorcioKeyPressed

    private void jCmb_ConsorcioPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioPopupMenuWillBecomeVisible
        this.searchCombo(this.jCmb_Consorcio);
        
    }//GEN-LAST:event_jCmb_ConsorcioPopupMenuWillBecomeVisible

    
    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtn_SalirActionPerformed
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaUnidades().setVisible(true);
            }
        });
    }
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Aceptar;
    private javax.swing.JButton jBtn_Cancelar;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JComboBox jCmb_Consorcio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxt_descripcion;
    // Fin de declaración de variables//GEN-END:variables
    
    public void searchCombo(JComboBox jc){
        
        String st=((JTextField)jc.getEditor().getEditorComponent()).getText();
        for(int i=0;i<jc.getModel().getSize();i++)
        {
            if(((String)jc.getItemAt(i)).contains(st)){
               jc.setSelectedIndex(i); 
               ((JTextField)jc.getEditor().getEditorComponent()).setText((String)jc.getSelectedItem());
              }
                
        }
    }
    class ComboConsorciosModel implements ComboBoxModel{
        
        Consorcio cons=new Consorcio();
        protected Object selected;
        private List lst;
         
        ComboConsorciosModel(){
            this.setLst(cons.buscarActivos());
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Consorcio consor=new Consorcio();
                consor=(Consorcio)getLst().get(index);
		return consor.getDenominacion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }

     
    }

      //Método para validar Empty Fields
        private boolean validateFields(){
            if (this.jCmb_Consorcio.getSelectedIndex()==-1){
                JOptionPane.showMessageDialog(null,"Debe seleccionar el consorcio al cual pertenece la unidad");
                this.jCmb_Consorcio.requestFocus();
                return false;
            }
            if (this.jTxt_descripcion.getText().trim().length()==0){
                JOptionPane.showMessageDialog(null,"Debe ingresar una descripción");
                this.jTxt_descripcion.requestFocus();
                return false;
            }
            if (this.jTxt_descripcion.getText().trim().length()>30){
                JOptionPane.showMessageDialog(null,"La descripción debe contener menos de 30 caracteres");
                this.jTxt_descripcion.requestFocus();
                return false;
            }
            return true;
        }
    
        private void limpiar(){
            //this.jCmb_Consorcio.setSelectedIndex(-1);
            this.jTxt_descripcion.setText("");
        }

    public Unidad getUnidadUpdated() {
        return unidadUpdated;
    }

    public void setUnidadUpdated(Unidad unidadUpdated) {
        this.unidadUpdated = unidadUpdated;
    }
    
    public int buscarUnidadCombo(Unidad uni)
    {
        List lst=((ComboConsorciosModel)this.jCmb_Consorcio.getModel()).getLst();
        Iterator it=lst.iterator();
        int index=0;
        while (it.hasNext()){
            Consorcio con = (Consorcio)it.next();
            if (con.getCodigo()==uni.getConsorcio().getCodigo()){
                return index;
            }
            index++;
        }
        return -1;
            
    }

    public ConsultaUnidad getCu() {
        return cu;
    }

    public void setCu(ConsultaUnidad cu) {
        this.cu = cu;
    }
   
}
