/*
 * AltaPagos.java
 *
 * Created on 20 de diciembre de 2007, 19:59
 */

package expensav20.GUI;

import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ListDataListener;
import javax.swing.text.MaskFormatter;
import model.Concepto;
import model.Consorcio;
import model.CtaCte;
import model.Pago;
import model.Propiedades;
import model.Unidad;

/**
 *
 * @author  Javier
 */
public class AltaPagos extends javax.swing.JFrame {
    
    /** Creates new form AltaPagos */
    public AltaPagos() {
        initComponents();
        this.jCmb_Concepto.setModel(new ComboConceptosModel());
        this.jCmb_Consorcio.setModel(new ComboConsorciosModel());
        this.jCmb_Unidad.setModel(new ComboUnidadesModel());
        this.jCmb_Concepto.updateUI();
        this.jCmb_Consorcio.updateUI();
        this.jCmb_Unidad.updateUI();
        try {
            MaskFormatter mascara_fecha = new MaskFormatter("##/##/####");
            mascara_fecha.install(this.jFtf_Fecha);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        this.jFtf_Fecha.setText(sdf.format(Calendar.getInstance().getTime()).toString());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCmb_Consorcio = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jCmb_Unidad = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTxt_Propietario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxt_Inquilino = new javax.swing.JTextField();
        jBtn_Popular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBtn_Detalle = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTxt_Monto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCmb_Concepto = new javax.swing.JComboBox();
        jFtf_Fecha = new javax.swing.JFormattedTextField();
        jFtf_Importe = new javax.swing.JFormattedTextField();
        jBtn_Aceptar = new javax.swing.JButton();
        jBtn_Cancelar = new javax.swing.JButton();
        jBtn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de Pagos");
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidad"));
        jLabel1.setText("Consorcio:");

        jCmb_Consorcio.setEditable(true);
        jCmb_Consorcio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Galeria Norte", "Edificio Pajas Blancas" }));
        jCmb_Consorcio.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_ConsorcioPopupMenuWillBecomeVisible(evt);
            }
        });
        jCmb_Consorcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_ConsorcioActionPerformed(evt);
            }
        });

        jLabel2.setText("Unidad:");

        jCmb_Unidad.setEditable(true);
        jCmb_Unidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Local 1", "Local 2", "Local 3" }));
        jCmb_Unidad.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_UnidadPopupMenuWillBecomeVisible(evt);
            }
        });
        jCmb_Unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_UnidadActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/zoom.png")));
        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Propietario:");

        jTxt_Propietario.setBackground(new java.awt.Color(204, 204, 204));
        jTxt_Propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_PropietarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Inquilino:");

        jTxt_Inquilino.setBackground(new java.awt.Color(204, 204, 204));

        jBtn_Popular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/hourglass_add.png")));
        jBtn_Popular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_PopularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCmb_Consorcio, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Popular, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxt_Propietario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCmb_Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jTxt_Inquilino, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jCmb_Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jCmb_Consorcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtn_Popular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxt_Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTxt_Inquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Deuda"));
        jBtn_Detalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/cog_go.png")));
        jBtn_Detalle.setText("Ver Detalle");
        jBtn_Detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_DetalleActionPerformed(evt);
            }
        });

        jLabel7.setText("Monto Adeudado:");

        jTxt_Monto.setBackground(new java.awt.Color(204, 204, 204));
        jTxt_Monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_MontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtn_Detalle)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(jTxt_Monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jBtn_Detalle))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pago"));
        jLabel8.setText("Fecha:");

        jLabel9.setText("Concepto:");

        jLabel10.setText("Monto:");

        jCmb_Concepto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Art\u00edculo 1", "Art\u00edculo 2", "Art\u00edculo 3", "Art\u00edculo 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jFtf_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFtf_Importe, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(jCmb_Concepto, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jFtf_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jFtf_Importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCmb_Concepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/tick.png")));
        jBtn_Aceptar.setText("Aceptar");
        jBtn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AceptarActionPerformed(evt);
            }
        });

        jBtn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/cross.png")));
        jBtn_Cancelar.setText("Cancelar");
        jBtn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CancelarActionPerformed(evt);
            }
        });

        jBtn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/door_out.png")));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(376, Short.MAX_VALUE)
                        .addComponent(jBtn_Aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Salir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Salir)
                    .addComponent(jBtn_Cancelar)
                    .addComponent(jBtn_Aceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CancelarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_jBtn_CancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.jCmb_Unidad.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar una unidad previamente");
            return;
        }
        Unidad uni = (Unidad)((ComboUnidadesModel)this.jCmb_Unidad.getModel()).getLst().get(this.jCmb_Unidad.getSelectedIndex());
        this.jTxt_Inquilino.setText("");
        if (uni.getInquilino()!=null){
            this.jTxt_Inquilino.setText(uni.getInquilino().getNombre());
        }
        if (uni.getPropietario()!=null){
            this.jTxt_Propietario.setText(uni.getPropietario().getNombre());
        }
        CtaCte cc=new CtaCte();
        cc.cargarCta(uni);
        Propiedades prop=new Propiedades();
        DecimalFormat nf=(DecimalFormat) DecimalFormat.getInstance(Locale.ENGLISH);
        nf.setGroupingUsed(false);
        nf.setRoundingMode(RoundingMode.HALF_UP);
        Map props=prop.buscarTodas();
        int cant_digitos= Integer.parseInt((String) props.get("cantidad_decimales_liquidacon"));
        nf.setMaximumFractionDigits(cant_digitos);
        this.jTxt_Monto.setText(nf.format(cc.getSaldo()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtn_DetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_DetalleActionPerformed
        if (this.jCmb_Unidad.getSelectedIndex()==-1){
            return;
        }
        Unidad uni = (Unidad)((ComboUnidadesModel)this.jCmb_Unidad.getModel()).getLst().get(this.jCmb_Unidad.getSelectedIndex());
        if (uni!=null){
            ConsultaCuentaCorriente ctaCte=new ConsultaCuentaCorriente(uni);
            ctaCte.disableEliminar();
            ctaCte.setVisible(true);
        }
    }//GEN-LAST:event_jBtn_DetalleActionPerformed

    private void jBtn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AceptarActionPerformed
        if (!validateFields())
            return;
        if (Double.valueOf(this.jTxt_Monto.getText()).compareTo(Double.valueOf(this.jFtf_Importe.getText()))<0){
            JOptionPane.showMessageDialog(this.getContentPane(),"El monto ingresado es superior al monto que se debe");
            return;
        }
        Unidad uni = (Unidad)((ComboUnidadesModel)this.jCmb_Unidad.getModel()).getLst().get(this.jCmb_Unidad.getSelectedIndex());
        /*if(existePago(uni)){
            JOptionPane.showMessageDialog(this.getContentPane(),"Ya fue cargado un pago a la unidad en la fecha");
            return;
        }
        */  
        Pago pago=new Pago();
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
        Concepto conc=(Concepto)((ComboConceptosModel)this.jCmb_Concepto.getModel()).getLst().get(this.jCmb_Concepto.getSelectedIndex());
        pago.setConcepto(conc);
        try {
            pago.setFecha(sdf.parse(this.jFtf_Fecha.getText()));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        pago.setImporte(Double.valueOf(this.jFtf_Importe.getText()));        
        if (pago.generarPago(uni)){
            JOptionPane.showMessageDialog(this.getContentPane(),"El Pago fue guardado correctamente");
            this.jTxt_Monto.setText("");
            this.jFtf_Importe.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this.getContentPane(),"Ha ocurrido un problema, por favor intente nuevamente");
        }
    }//GEN-LAST:event_jBtn_AceptarActionPerformed

    private void jCmb_UnidadPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_UnidadPopupMenuWillBecomeVisible
        this.searchCombo(this.jCmb_Unidad);
    }//GEN-LAST:event_jCmb_UnidadPopupMenuWillBecomeVisible

    private void jCmb_UnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_UnidadActionPerformed
        ((JTextField)this.jCmb_Unidad.getEditor().getEditorComponent()).setText(((String)this.jCmb_Unidad.getSelectedItem())); 
    }//GEN-LAST:event_jCmb_UnidadActionPerformed

    private void jCmb_ConsorcioPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioPopupMenuWillBecomeVisible
        this.searchCombo(this.jCmb_Consorcio);
    }//GEN-LAST:event_jCmb_ConsorcioPopupMenuWillBecomeVisible

    private void jCmb_ConsorcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioActionPerformed
        ((JTextField)this.jCmb_Consorcio.getEditor().getEditorComponent()).setText(((String)this.jCmb_Consorcio.getSelectedItem()));        
    }//GEN-LAST:event_jCmb_ConsorcioActionPerformed

    private void jBtn_PopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_PopularActionPerformed
        Consorcio cons=new Consorcio();
        if (this.jCmb_Consorcio.getSelectedIndex()!=-1){
            cons=(Consorcio)((ComboConsorciosModel)this.jCmb_Consorcio.getModel()).getLst().get(this.jCmb_Consorcio.getSelectedIndex());
            Unidad uni=new Unidad();
            ((ComboUnidadesModel)this.jCmb_Unidad.getModel()).setLst(uni.buscarxConsorcioActivas(cons));
            this.jCmb_Unidad.setSelectedIndex(-1);
            this.jCmb_Unidad.updateUI();
        }
    }//GEN-LAST:event_jBtn_PopularActionPerformed

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtn_SalirActionPerformed

    private void jTxt_PropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_PropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_PropietarioActionPerformed

    private void jTxt_MontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_MontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_MontoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaPagos().setVisible(true);
            }
        });
    }
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Aceptar;
    private javax.swing.JButton jBtn_Cancelar;
    private javax.swing.JButton jBtn_Detalle;
    private javax.swing.JButton jBtn_Popular;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCmb_Concepto;
    private javax.swing.JComboBox jCmb_Consorcio;
    private javax.swing.JComboBox jCmb_Unidad;
    private javax.swing.JFormattedTextField jFtf_Fecha;
    private javax.swing.JFormattedTextField jFtf_Importe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTxt_Inquilino;
    private javax.swing.JTextField jTxt_Monto;
    private javax.swing.JTextField jTxt_Propietario;
    // Fin de declaración de variables//GEN-END:variables
 
    
    class ComboConsorciosModel implements ComboBoxModel{
        
        Consorcio cons=new Consorcio();
        protected Object selected;
        private List lst;
         
        ComboConsorciosModel(){
            this.setLst(cons.buscarActivos());
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
            Consorcio consor=new Consorcio();
            consor=(Consorcio)getLst().get(index);
            return consor.getDenominacion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    
    class ComboUnidadesModel implements ComboBoxModel{
        
        Unidad uni=new Unidad();
        protected Object selected;
        private List lst;
         
        ComboUnidadesModel(){
            lst=new ArrayList();
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Unidad uni=new Unidad();
                uni=(Unidad)getLst().get(index);
		return uni.getConsorcio().getDenominacion() + "-" + uni.getDescripcion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    
    class ComboConceptosModel implements ComboBoxModel{
        
        Concepto conc=new Concepto();
        protected Object selected;
        private List lst=new ArrayList();
         
        ComboConceptosModel(){
            this.setLst(conc.buscarVigentesxTipo(true,"Haber"));
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
            Concepto conc=new Concepto();
            conc=(Concepto)getLst().get(index);
            return conc.getNombre();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    
    public void searchCombo(JComboBox jc){   
        String st=((JTextField)jc.getEditor().getEditorComponent()).getText();
        for(int i=0;i<jc.getModel().getSize();i++)
        {
           if(((String)jc.getItemAt(i)).contains(st)){
           jc.setSelectedIndex(i); 
           ((JTextField)jc.getEditor().getEditorComponent()).setText((String)jc.getSelectedItem());
           }
                  
        }
   }
    
   private boolean validateFields(){
 
        if (this.jFtf_Fecha.getText().length()==0){
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar la fecha de pago");
            this.jFtf_Fecha.requestFocus();
            return false;
        }
        if(this.jFtf_Importe.getText().length()==0){
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar el importe del pago");
            this.jFtf_Importe.requestFocus();
            return false;
        }
        if(this.jCmb_Concepto.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar el concepto");
            this.jCmb_Concepto.requestFocus();
            return false;
        }
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        df.setLenient(false);
        
        try {
            df.parse(this.jFtf_Fecha.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar una fecha válida");
            this.jFtf_Fecha.requestFocus();
            return false;  
        }
        try {
            Double.parseDouble(this.jFtf_Importe.getText());
        } catch(Exception e){
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar un importe válido");
            this.jFtf_Importe.requestFocus();
            return false;    
        }
        return true;
    }
   public void limpiar(){
       this.jCmb_Consorcio.setSelectedIndex(-1);
       this.jCmb_Unidad.setSelectedIndex(-1);
       this.jTxt_Inquilino.setText("");
       this.jTxt_Monto.setText("");
       this.jTxt_Propietario.setText("");
       this.jCmb_Concepto.setSelectedIndex(-1);
       this.jFtf_Fecha.setText("");
       this.jFtf_Importe.setText("");
   }
   
   public boolean existePago(Unidad uni){
       boolean return_value=false;
       Calendar cal=Calendar.getInstance();
       Date today=cal.getTime();
       Pago pag=new Pago();
       List lst=pag.buscarSaldoxCriteria(uni,null,null,today,today);
       if (lst.size()>0){
           return_value=true;
       }
       return return_value;
   }
   
}
