/*
 * AltaInquilinos.java
 *
 * Created on 20 de diciembre de 2007, 21:16
 */

package expensav20.GUI;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ListDataListener;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;
import model.Consorcio;
import model.Inquilino;
import model.Provincia;
import model.Unidad;

/**
 *
 * @author  Javier
 */
public class AltaInquilinos extends javax.swing.JFrame {
    
    private Inquilino inquilinoUpdated = new Inquilino();
    private ConsultaInquilino ci=new ConsultaInquilino();
    /** Creates new form AltaInquilinos */
    public AltaInquilinos() {
        initComponents();
        this.jCmb_Consorcio.setModel(new ComboConsorciosModel());
        this.jCmb_Consorcio.setEditable(true);
        this.jCmb_Consorcio.updateUI();
        this.jCmb_Provincia.setModel(new ComboProvinciasModel());
        this.jCmb_Provincia.setSelectedIndex(0);
        this.jCmb_Provincia.updateUI();
        this.jCmb_Unidad.setModel(new ComboUnidadesModel());
        this.jCmb_Unidad.setEditable(true);
        this.jCmb_Unidad.updateUI();
        
        this.jTlb_Unidades.setModel(new TableUnidadesModel());
        this.jTlb_Unidades.updateUI();
        
        //Inicios de JTextFormatters
        try {
            MaskFormatter mascara_cuit = new MaskFormatter("##-########-#");
            MaskFormatter mascara_cp = new MaskFormatter("A####AAA");
            mascara_cuit.setValueContainsLiteralCharacters(false);
            mascara_cp.setValueContainsLiteralCharacters(false);
            mascara_cuit.install(this.jFTxt_Cuit);
            mascara_cp.install(this.jFTxt_CP);
            
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }
    
    public AltaInquilinos(Inquilino inq,ConsultaInquilino ci) {
        initComponents();
        this.jCmb_Consorcio.setModel(new ComboConsorciosModel());
        this.jCmb_Consorcio.setEditable(true);
        this.jCmb_Consorcio.updateUI();
        this.jCmb_Provincia.setModel(new ComboProvinciasModel());
        this.jCmb_Provincia.setSelectedIndex(0);
        this.jCmb_Provincia.updateUI();
        this.jCmb_Unidad.setModel(new ComboUnidadesModel());
        this.jCmb_Unidad.setEditable(true);
        this.jCmb_Unidad.updateUI();
        
        this.jTlb_Unidades.setModel(new TableUnidadesModel());
        this.jTlb_Unidades.updateUI();
        
        //Inicios de JTextFormatters
        try {
            MaskFormatter mascara_cuit = new MaskFormatter("##-########-#");
            MaskFormatter mascara_cp = new MaskFormatter("A####AAA");
            mascara_cuit.setValueContainsLiteralCharacters(false);
            mascara_cp.setValueContainsLiteralCharacters(false);
            mascara_cuit.install(this.jFTxt_Cuit);
            mascara_cp.install(this.jFTxt_CP);
            
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        this.jTxt_Domicilio.setText(inq.getDomicilio());
        this.jTxt_Localidad.setText(inq.getLocalidad());
        this.jTxt_Nombre.setText(inq.getNombre());
        this.jFTxt_CP.setText(inq.getCp().trim());
        this.jFTxt_Cuit.setText(String.valueOf(inq.getCuit()));
        this.jCmb_Provincia.setSelectedIndex(this.buscarProvinciaCombo(inq.getProvincia()));
        this.jCmb_Provincia.updateUI();
        ((TableUnidadesModel)this.jTlb_Unidades.getModel()).setLst(inq.getUnidades());
        this.jTlb_Unidades.updateUI();
        this.setInquilinoUpdated(inq);
        this.setCi(ci);
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jTxt_Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCmb_Provincia = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTxt_Localidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jCmb_Consorcio = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jCmb_Unidad = new javax.swing.JComboBox();
        jBtn_Agregar = new javax.swing.JButton();
        jBtn_Quitar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTlb_Unidades = new javax.swing.JTable();
        jBtn_Popular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFTxt_Cuit = new javax.swing.JFormattedTextField();
        jFTxt_CP = new javax.swing.JFormattedTextField();
        jTxt_Domicilio = new javax.swing.JTextField();
        jBtn_Aceptar = new javax.swing.JButton();
        jBtn_Cancelar = new javax.swing.JButton();
        jBtn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de Inquilinos");
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Inquilino"));

        jLabel4.setText("Domicilio:");

        jLabel5.setText("CUIT:");

        jLabel6.setText("CP:");

        jCmb_Provincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cordoba", "La Pampa" }));

        jLabel7.setText("Provincia:");

        jLabel8.setText("Localidad:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel9.setText("Consorcios:");

        jCmb_Consorcio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Art\u00edculo 1", "Art\u00edculo 2", "Art\u00edculo 3", "Art\u00edculo 4" }));
        jCmb_Consorcio.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_ConsorcioPopupMenuWillBecomeVisible(evt);
            }
        });
        jCmb_Consorcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_ConsorcioActionPerformed(evt);
            }
        });

        jLabel10.setText("Unidades:");

        jCmb_Unidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Art\u00edculo 1", "Art\u00edculo 2", "Art\u00edculo 3", "Art\u00edculo 4" }));
        jCmb_Unidad.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_UnidadPopupMenuWillBecomeVisible(evt);
            }
        });
        jCmb_Unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_UnidadActionPerformed(evt);
            }
        });

        jBtn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/table_add.png")));
        jBtn_Agregar.setText("Agregar");
        jBtn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AgregarActionPerformed(evt);
            }
        });

        jBtn_Quitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/table_delete.png")));
        jBtn_Quitar.setText("Quitar");
        jBtn_Quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_QuitarActionPerformed(evt);
            }
        });

        jTlb_Unidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4"
            }
        ));
        jScrollPane2.setViewportView(jTlb_Unidades);

        jBtn_Popular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/hourglass_add.png")));
        jBtn_Popular.setAlignmentY(0.0F);
        jBtn_Popular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_Popular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_PopularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCmb_Consorcio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCmb_Unidad, 0, 248, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBtn_Agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_Quitar))
                            .addComponent(jBtn_Popular, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jCmb_Consorcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtn_Popular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jBtn_Quitar)
                    .addComponent(jBtn_Agregar)
                    .addComponent(jCmb_Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel3.setText("Nombre y Apellido:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxt_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(jFTxt_Cuit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCmb_Provincia, 0, 297, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxt_Localidad, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTxt_CP, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxt_Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFTxt_Cuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxt_Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jFTxt_CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_Localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCmb_Provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/tick.png")));
        jBtn_Aceptar.setText("Aceptar");
        jBtn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AceptarActionPerformed(evt);
            }
        });

        jBtn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/cross.png")));
        jBtn_Cancelar.setText("Cancelar");
        jBtn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CancelarActionPerformed(evt);
            }
        });

        jBtn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/door_out.png")));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtn_Aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Salir)
                    .addComponent(jBtn_Cancelar)
                    .addComponent(jBtn_Aceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_PopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_PopularActionPerformed
        Consorcio cons=new Consorcio();
        if (this.jCmb_Consorcio.getSelectedIndex()!=-1){
            cons=(Consorcio)((ComboConsorciosModel)this.jCmb_Consorcio.getModel()).getLst().get(this.jCmb_Consorcio.getSelectedIndex());
            Unidad uni=new Unidad();
            ((ComboUnidadesModel)this.jCmb_Unidad.getModel()).setLst(uni.buscarxConsorcioNoAlquiladas(cons));
            this.jCmb_Unidad.setSelectedIndex(-1);
            this.jCmb_Unidad.updateUI();
        }
    }//GEN-LAST:event_jBtn_PopularActionPerformed

    private void jBtn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CancelarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_jBtn_CancelarActionPerformed

    private void jBtn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AceptarActionPerformed
        if (this.validateFields()==false)
            return;
        Inquilino inq = new Inquilino();
        inq.setCp(this.jFTxt_CP.getText().trim());
        if (this.jFTxt_Cuit.getText().replace("-","").trim().length()>0){
            inq.setCuit(Long.parseLong(this.jFTxt_Cuit.getText().trim().replace("-","")));
        }
        if(this.jTxt_Domicilio.getText().length()>30){
            inq.setDomicilio(this.jTxt_Domicilio.getText().trim().substring(0,30));
        }
        else{
            inq.setDomicilio(this.jTxt_Domicilio.getText());
        }
            
        
        inq.setLocalidad(this.jTxt_Localidad.getText().trim());
        inq.setNombre(this.jTxt_Nombre.getText().trim());
        inq.setProvincia((Provincia)((ComboProvinciasModel)this.jCmb_Provincia.getModel()).getLst().get(this.jCmb_Provincia.getSelectedIndex()));
        inq.setUnidades(((TableUnidadesModel)this.jTlb_Unidades.getModel()).getLst());
        if (this.getInquilinoUpdated().getCodigo()==0){
            if (inq.validaExiste()>0){
                JOptionPane.showMessageDialog(this.getContentPane(),"Ya existe un inquilino con ese nombre. Cambie el nombre del inquilino o agregue las unidades al inquilino existente");                
                return;
            }
            inq.guardar();
            if (inq.getCodigo()!=0){
                JOptionPane.showMessageDialog(this.getContentPane(),"El Inquilino se guardó correctamente");
                this.limpiar();
            }
            else{
                JOptionPane.showMessageDialog(this.getContentPane(),"Ocurrió un problema, por favor intente nuevamente");
            }
        }
        else{
            inq.setCodigo(this.getInquilinoUpdated().getCodigo());
            if (inq.modificar()!=0){
                JOptionPane.showMessageDialog(this.getContentPane(),"El inquilino fue modificado correctamente");
                this.getCi().actualizar();
            }
            else{
                JOptionPane.showMessageDialog(this.getContentPane(),"Ocurrió un problema, por favor intente nuevamente");
            }
        }
               
    }//GEN-LAST:event_jBtn_AceptarActionPerformed

    private void jBtn_QuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_QuitarActionPerformed
        if (this.jTlb_Unidades.getRowCount()!=0){
            ((TableUnidadesModel)this.jTlb_Unidades.getModel()).getLst().remove(this.jTlb_Unidades.getSelectedRow());
            this.jTlb_Unidades.updateUI();
            if (this.jTlb_Unidades.getRowCount()!=0){
                this.jTlb_Unidades.setRowSelectionInterval(0,0);
            }
         }

    }//GEN-LAST:event_jBtn_QuitarActionPerformed

    private void jBtn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AgregarActionPerformed
        Unidad uni=new Unidad();
        if (this.jCmb_Unidad.getSelectedIndex()!=-1){
            uni=(Unidad)((ComboUnidadesModel)this.jCmb_Unidad.getModel()).getLst().get(this.jCmb_Unidad.getSelectedIndex());
            ((TableUnidadesModel)this.jTlb_Unidades.getModel()).getLst().add(uni);
            this.jTlb_Unidades.updateUI();
            if (this.jTlb_Unidades.getRowCount()!=0){
                this.jTlb_Unidades.setRowSelectionInterval(0,0);
            }
        }
  
    }//GEN-LAST:event_jBtn_AgregarActionPerformed

    private void jCmb_UnidadPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_UnidadPopupMenuWillBecomeVisible
        this.searchCombo(this.jCmb_Consorcio);
    }//GEN-LAST:event_jCmb_UnidadPopupMenuWillBecomeVisible

    private void jCmb_ConsorcioPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioPopupMenuWillBecomeVisible
        this.searchCombo(this.jCmb_Consorcio);
    }//GEN-LAST:event_jCmb_ConsorcioPopupMenuWillBecomeVisible

    private void jCmb_UnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_UnidadActionPerformed
                ((JTextField)this.jCmb_Unidad.getEditor().getEditorComponent()).setText(((String)this.jCmb_Unidad.getSelectedItem()));        
    }//GEN-LAST:event_jCmb_UnidadActionPerformed

    private void jCmb_ConsorcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioActionPerformed
        ((JTextField)this.jCmb_Consorcio.getEditor().getEditorComponent()).setText(((String)this.jCmb_Consorcio.getSelectedItem()));        
    }//GEN-LAST:event_jCmb_ConsorcioActionPerformed

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtn_SalirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaInquilinos().setVisible(true);
            }
        });
    }
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Aceptar;
    private javax.swing.JButton jBtn_Agregar;
    private javax.swing.JButton jBtn_Cancelar;
    private javax.swing.JButton jBtn_Popular;
    private javax.swing.JButton jBtn_Quitar;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JComboBox jCmb_Consorcio;
    private javax.swing.JComboBox jCmb_Provincia;
    private javax.swing.JComboBox jCmb_Unidad;
    private javax.swing.JFormattedTextField jFTxt_CP;
    private javax.swing.JFormattedTextField jFTxt_Cuit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTlb_Unidades;
    private javax.swing.JTextField jTxt_Domicilio;
    private javax.swing.JTextField jTxt_Localidad;
    private javax.swing.JTextField jTxt_Nombre;
    // Fin de declaración de variables//GEN-END:variables
    
    
    class ComboProvinciasModel implements ComboBoxModel{
        
        Provincia prov=new Provincia();
        protected Object selected;
        private List lst;
         
        ComboProvinciasModel(){
            this.setLst(prov.buscar());
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Provincia prov=new Provincia();
                prov=(Provincia)getLst().get(index);
		return prov.getDescripcion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }

      class ComboConsorciosModel implements ComboBoxModel{
        
        Consorcio cons=new Consorcio();
        protected Object selected;
        private List lst;
         
        ComboConsorciosModel(){
            this.setLst(cons.buscarActivos());
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Consorcio consor=new Consorcio();
                consor=(Consorcio)getLst().get(index);
		return consor.getDenominacion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    
    class ComboUnidadesModel implements ComboBoxModel{
        
        Unidad uni=new Unidad();
        protected Object selected;
        private List lst;
         
        ComboUnidadesModel(){
            lst=new ArrayList();
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Unidad uni=new Unidad();
                uni=(Unidad)getLst().get(index);
		return uni.getConsorcio().getDenominacion() + "-" + uni.getDescripcion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
      

    class TableUnidadesModel implements TableModel{
        
        Unidad uni=new Unidad();     
        protected Object selected;
        private List lst=new ArrayList();
         
        TableUnidadesModel(){
           
        }
        
        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }

        public int getRowCount() {
            return this.getLst().size();
        }

        public int getColumnCount() {
            return 2;
        }

        public String getColumnName(int columnIndex) {
            switch (columnIndex){
                case 0: 
                    return "Consorcio";
                case 1: 
                    return "Unidad";
            }
            return "";
        }
        public Class<?> getColumnClass(int columnIndex) {
            return this.getClass();
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
       

        public Object getValueAt(int rowIndex, int columnIndex) {
            switch(columnIndex){
                case 1:
                    return ((Unidad)this.getLst().get(rowIndex)).getDescripcion();
                case 0:
                    return ((Unidad)this.getLst().get(rowIndex)).getConsorcio().getDenominacion();
            }
            return null;
        }
        

        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
        }

        public void addTableModelListener(TableModelListener l) {
        }

        public void removeTableModelListener(TableModelListener l) {
        }
    }

      
    public void searchCombo(JComboBox jc){   
        String st=((JTextField)jc.getEditor().getEditorComponent()).getText();
        for(int i=0;i<jc.getModel().getSize();i++)
        {
           if(((String)jc.getItemAt(i)).contains(st)){
           jc.setSelectedIndex(i); 
           ((JTextField)jc.getEditor().getEditorComponent()).setText((String)jc.getSelectedItem());
           }
                  
        }
   }
   
   public void limpiar(){
       this.jTxt_Domicilio.setText("");
       this.jTxt_Localidad.setText("");
       this.jTxt_Nombre.setText("");
       this.jCmb_Consorcio.setSelectedIndex(-1);
       this.jCmb_Provincia.setSelectedIndex(-1);
       this.jCmb_Unidad.setSelectedIndex(-1);
       ((ComboUnidadesModel)this.jCmb_Unidad.getModel()).getLst().clear();
       this.jCmb_Unidad.updateUI();
       ((TableUnidadesModel)this.jTlb_Unidades.getModel()).getLst().clear();
       this.jTlb_Unidades.updateUI();
       this.jFTxt_CP.setText("");
       this.jFTxt_Cuit.setText("");
   }
   
   
    private boolean validateFields(){ 

        if(this.jTxt_Nombre.getText().trim().length()==0 || this.jTxt_Nombre.getText().trim().length()>35){
            JOptionPane.showMessageDialog(this.getContentPane(),"El nombre no puede estar vacío o contener mas de 35 caracteres");
            this.jTxt_Nombre.requestFocus();
            return false;
        }

        if (this.jFTxt_Cuit.getText().replace("-","").trim().length()<11 && this.jFTxt_Cuit.getText().replace("-","").trim().length()>0){
          JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar un CUIT válido");
          this.jFTxt_Cuit.requestFocus();
          return false;
        }

        
        if (this.jTxt_Domicilio.getText().trim().length()==0){
          JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar un domicilio");
          this.jTxt_Domicilio.requestFocus();
          return false;
        }
        

        
        if(this.jTxt_Localidad.getText().trim().length()==0 || this.jTxt_Localidad.getText().trim().length()>30){
            JOptionPane.showMessageDialog(this.getContentPane(),"La localidad no puede estar vacío o contener mas de 30 caracteres");
            this.jTxt_Localidad.requestFocus();
            return false;
        }
        
        if (this.jFTxt_CP.getText().trim().length()==0){
          JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar un código postal válido. 4 Dígitos");
          this.jFTxt_CP.requestFocus();
          return false;
        }
        
        if (this.jTlb_Unidades.getRowCount()==0){
          JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar al menos una propiedad para el propietario");
          this.jCmb_Consorcio.requestFocus();
          return false;
        }
        
        return true;
    }
    public int buscarProvinciaCombo(Provincia prov2)
    {
        List lst=((ComboProvinciasModel)this.jCmb_Provincia.getModel()).getLst();
        Iterator it=lst.iterator();
        int index=0;
        while (it.hasNext()){
            Provincia prov = (Provincia)it.next();
            if (prov.getCodigo()==prov2.getCodigo()){
                return index;
            }
            index++;
        }
        return -1;
            
    }

    public Inquilino getInquilinoUpdated() {
        return inquilinoUpdated;
    }

    public void setInquilinoUpdated(Inquilino inquilinoUpdated) {
        this.inquilinoUpdated = inquilinoUpdated;
    }

    public ConsultaInquilino getCi() {
        return ci;
    }

    public void setCi(ConsultaInquilino ci) {
        this.ci = ci;
    }
}
