/*
 * AltaTransferencia.java
 *
 * Created on 20 de diciembre de 2007, 21:08
 */

package expensav20.GUI;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ListDataListener;
import javax.swing.text.MaskFormatter;
import model.Consorcio;
import model.GastoImputado;
import model.Unidad;

/**
 *
 * @author  Javier
 */
public class AltaTransferencia extends javax.swing.JFrame {
    private GastoImputado giUpdated = new GastoImputado();
    private ConsultaGastosNoImp cci = new ConsultaGastosNoImp();
    /** Creates new form AltaTransferencia */
    public AltaTransferencia(GastoImputado gi,ConsultaGastosNoImp cci) {
        initComponents();
        try {
            MaskFormatter mascara_periodo = new MaskFormatter("##/####");
            mascara_periodo.install(this.jFtf_Periodo);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        SimpleDateFormat sdf=new SimpleDateFormat("MM/yyyy");
        this.jCmb_Consorcio_Desde.setModel(new ComboConsorciosDesdeModel());
        this.jCmb_Consorcio_Hasta.setModel(new ComboConsorciosHastaModel());
        this.jCmb_Unidad_Desde.setModel(new ComboUnidadesDesdeModel());
        this.jCmb_Unidad_Hasta.setModel(new ComboUnidadesHastaModel());
        this.jCmb_Consorcio_Desde.updateUI();
        this.jCmb_Consorcio_Hasta.updateUI();
        this.jCmb_Unidad_Desde.updateUI();
        this.jCmb_Unidad_Hasta.updateUI();
        Unidad uni = new Unidad();
        this.jCmb_Consorcio_Desde.setSelectedIndex(this.buscarConsorcioDesdeCombo(gi.getConsorcio()));
        this.jCmb_Consorcio_Desde.updateUI();
        this.jCmb_Unidad_Hasta.setEnabled(false);
        if(!gi.getConcepto().getCoeficiente().isDistribuible()){
            ((ComboUnidadesDesdeModel)this.jCmb_Unidad_Desde.getModel()).setLst(uni.buscarxConsorcioActivas(gi.getConsorcio()));
            this.jCmb_Unidad_Desde.updateUI();
            this.jCmb_Unidad_Desde.setSelectedIndex(this.buscarUnidadDesdeCombo(gi.getUnidad()));
            this.jCmb_Unidad_Desde.updateUI();
            this.jCmb_Unidad_Hasta.setEnabled(true);
        }
        this.jTxt_Concepto.setText(gi.getConcepto().getNombre());
        this.jTxt_Descripcion.setText(gi.getDescripcion());
        this.jFtf_Periodo.setText(sdf.format(gi.getPeriodo()));
        this.jTxt_Monto.setText(gi.getImporte().toString());
        this.setGiUpdated(gi);
        this.setCci(cci);
                
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxt_Concepto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxt_Monto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jCmb_Consorcio_Desde = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jCmb_Unidad_Desde = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCmb_Consorcio_Hasta = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jCmb_Unidad_Hasta = new javax.swing.JComboBox();
        jBtn_Popular = new javax.swing.JButton();
        jFtf_Periodo = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxt_Descripcion = new javax.swing.JTextField();
        jBtn_Aceptar = new javax.swing.JButton();
        jBtn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transferencias");
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Transferencia"));
        jLabel1.setText("Concepto:");

        jTxt_Concepto.setText("Aguas Cordobesas");
        jTxt_Concepto.setEnabled(false);

        jLabel2.setText("Per\u00edodo:");

        jLabel3.setText("Monto:");

        jTxt_Monto.setText("400");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Desde"));
        jLabel4.setText("Consorcio:");

        jCmb_Consorcio_Desde.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Galeria Norte", "Edificio Pajas Blancas" }));
        jCmb_Consorcio_Desde.setEnabled(false);

        jLabel5.setText("Unidad:");

        jCmb_Unidad_Desde.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Local 1", "Local 2", "Local 3" }));
        jCmb_Unidad_Desde.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCmb_Consorcio_Desde, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCmb_Unidad_Desde, 0, 190, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCmb_Consorcio_Desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCmb_Unidad_Desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Hacia"));
        jLabel6.setText("Consorcio:");

        jCmb_Consorcio_Hasta.setEditable(true);
        jCmb_Consorcio_Hasta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Edificio Pajas Blancas", "Galeria Norte" }));
        jCmb_Consorcio_Hasta.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_Consorcio_HastaPopupMenuWillBecomeVisible(evt);
            }
        });
        jCmb_Consorcio_Hasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_Consorcio_HastaActionPerformed(evt);
            }
        });

        jLabel7.setText("Unidad:");

        jCmb_Unidad_Hasta.setEditable(true);
        jCmb_Unidad_Hasta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Departamento 5B" }));
        jCmb_Unidad_Hasta.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_Unidad_HastaPopupMenuWillBecomeVisible(evt);
            }
        });
        jCmb_Unidad_Hasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_Unidad_HastaActionPerformed(evt);
            }
        });

        jBtn_Popular.setText("...");
        jBtn_Popular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_PopularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCmb_Consorcio_Hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtn_Popular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCmb_Unidad_Hasta, 0, 163, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCmb_Consorcio_Hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jCmb_Unidad_Hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_Popular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Descripcion:");

        jTxt_Descripcion.setText("Aguas Cordobesas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt_Concepto, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                            .addComponent(jTxt_Descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxt_Monto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFtf_Periodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxt_Concepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxt_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFtf_Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxt_Monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jBtn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/tick.png")));
        jBtn_Aceptar.setText("Aceptar");
        jBtn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AceptarActionPerformed(evt);
            }
        });

        jBtn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/door_out.png")));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtn_Aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtn_Salir)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Salir)
                    .addComponent(jBtn_Aceptar))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AceptarActionPerformed
        if (!this.validateFields())
            return;
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        GastoImputado gi=new GastoImputado();
        gi.setConsorcio((Consorcio)((ComboConsorciosHastaModel)this.jCmb_Consorcio_Hasta.getModel()).getLst().get(this.jCmb_Consorcio_Hasta.getSelectedIndex()));
        gi.setDescripcion(this.jTxt_Descripcion.getText());
        try {
            gi.setPeriodo(df.parse("01/"+this.jFtf_Periodo.getText()));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        gi.setImporte(Double.valueOf(this.jTxt_Monto.getText()));
        gi.setCodigo(this.getGiUpdated().getCodigo());
        gi.setPeriodoGasto(this.getGiUpdated().getPeriodoGasto());
        if (!this.getGiUpdated().getConcepto().getCoeficiente().isDistribuible()){
            gi.setUnidad((Unidad)((ComboUnidadesHastaModel)this.jCmb_Unidad_Hasta.getModel()).getLst().get(this.jCmb_Unidad_Hasta.getSelectedIndex()));
        }        
        if (gi.transferir()!=0){
            JOptionPane.showMessageDialog(this.getContentPane(),"El gasto se ha transferido correctamente");
            this.getCci().actualizar();
        }
        else{
            JOptionPane.showMessageDialog(this.getContentPane(),"Ocurrió un problema, por favor intente nuevamente");
        }
            

        
    }//GEN-LAST:event_jBtn_AceptarActionPerformed

    private void jCmb_Unidad_HastaPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_Unidad_HastaPopupMenuWillBecomeVisible
        this.searchCombo(this.jCmb_Unidad_Hasta);
    }//GEN-LAST:event_jCmb_Unidad_HastaPopupMenuWillBecomeVisible

    private void jCmb_Unidad_HastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_Unidad_HastaActionPerformed
        ((JTextField)this.jCmb_Unidad_Hasta.getEditor().getEditorComponent()).setText(((String)this.jCmb_Unidad_Hasta.getSelectedItem()));        
    }//GEN-LAST:event_jCmb_Unidad_HastaActionPerformed

    private void jCmb_Consorcio_HastaPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_Consorcio_HastaPopupMenuWillBecomeVisible
        this.searchCombo(this.jCmb_Consorcio_Hasta);
    }//GEN-LAST:event_jCmb_Consorcio_HastaPopupMenuWillBecomeVisible

    private void jCmb_Consorcio_HastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_Consorcio_HastaActionPerformed
        ((JTextField)this.jCmb_Consorcio_Hasta.getEditor().getEditorComponent()).setText(((String)this.jCmb_Consorcio_Hasta.getSelectedItem()));        
    }//GEN-LAST:event_jCmb_Consorcio_HastaActionPerformed

    private void jBtn_PopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_PopularActionPerformed
        Consorcio cons=new Consorcio();
        if (this.jCmb_Consorcio_Hasta.getSelectedIndex()!=-1){
            cons=(Consorcio)((ComboConsorciosHastaModel)this.jCmb_Consorcio_Hasta.getModel()).getLst().get(this.jCmb_Consorcio_Hasta.getSelectedIndex());
            Unidad uni=new Unidad();
            ((ComboUnidadesHastaModel)this.jCmb_Unidad_Hasta.getModel()).setLst(uni.buscarxConsorcioActivas(cons));
            this.jCmb_Unidad_Hasta.setSelectedIndex(-1);
            this.jCmb_Unidad_Hasta.updateUI();
        }
    }//GEN-LAST:event_jBtn_PopularActionPerformed

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtn_SalirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaTransferencia(new GastoImputado(),new ConsultaGastosNoImp()).setVisible(true);
            }
        });
    }
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Aceptar;
    private javax.swing.JButton jBtn_Popular;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JComboBox jCmb_Consorcio_Desde;
    private javax.swing.JComboBox jCmb_Consorcio_Hasta;
    private javax.swing.JComboBox jCmb_Unidad_Desde;
    private javax.swing.JComboBox jCmb_Unidad_Hasta;
    private javax.swing.JFormattedTextField jFtf_Periodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTxt_Concepto;
    private javax.swing.JTextField jTxt_Descripcion;
    private javax.swing.JTextField jTxt_Monto;
    // Fin de declaración de variables//GEN-END:variables
    class ComboConsorciosDesdeModel implements ComboBoxModel{
        
        Consorcio cons=new Consorcio();
        protected Object selected;
        private List lst;
         
        ComboConsorciosDesdeModel(){
            this.setLst(cons.buscarActivos());
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Consorcio consor=new Consorcio();
                consor=(Consorcio)getLst().get(index);
		return consor.getDenominacion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    
    class ComboUnidadesDesdeModel implements ComboBoxModel{
        
        Unidad uni=new Unidad();
        protected Object selected;
        private List lst;
         
        ComboUnidadesDesdeModel(){
            lst=new ArrayList();
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Unidad uni=new Unidad();
                uni=(Unidad)getLst().get(index);
		return uni.getConsorcio().getDenominacion() + "-" + uni.getDescripcion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }

    class ComboConsorciosHastaModel implements ComboBoxModel{
        
        Consorcio cons=new Consorcio();
        protected Object selected;
        private List lst;
         
        ComboConsorciosHastaModel(){
            this.setLst(cons.buscarActivos());
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Consorcio consor=new Consorcio();
                consor=(Consorcio)getLst().get(index);
		return consor.getDenominacion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    
    class ComboUnidadesHastaModel implements ComboBoxModel{
        
        Unidad uni=new Unidad();
        protected Object selected;
        private List lst;
         
        ComboUnidadesHastaModel(){
            lst=new ArrayList();
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Unidad uni=new Unidad();
                uni=(Unidad)getLst().get(index);
		return uni.getConsorcio().getDenominacion() + "-" + uni.getDescripcion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    public int buscarConsorcioDesdeCombo(Consorcio conParam)
    {
        List lst=((ComboConsorciosDesdeModel)this.jCmb_Consorcio_Desde.getModel()).getLst();
        Iterator it=lst.iterator();
        int index=0;
        while (it.hasNext()){
            Consorcio consorc = (Consorcio)it.next();
            if (consorc.getCodigo()==conParam.getCodigo()){
                return index;
            }
            index++;
        }
        return -1;
            
    }
    public int buscarConsorcioHastaCombo(Consorcio conParam)
    {
        List lst=((ComboConsorciosHastaModel)this.jCmb_Consorcio_Hasta.getModel()).getLst();
        Iterator it=lst.iterator();
        int index=0;
        while (it.hasNext()){
            Consorcio consorc = (Consorcio)it.next();
            if (consorc.getCodigo()==conParam.getCodigo()){
                return index;
            }
            index++;
        }
        return -1;
            
    }
    public int buscarUnidadDesdeCombo(Unidad uniParam)
    {
        List lst=((ComboUnidadesDesdeModel)this.jCmb_Unidad_Desde.getModel()).getLst();
        Iterator it=lst.iterator();
        int index=0;
        while (it.hasNext()){
            Unidad uni = (Unidad)it.next();
            if (uni.getCodigo()==uniParam.getCodigo()){
                return index;
            }
            index++;
        }
        return -1;
            
    }
    public int buscarUnidadHastaCombo(Unidad uniParam)
    {
        List lst=((ComboUnidadesDesdeModel)this.jCmb_Unidad_Hasta.getModel()).getLst();
        Iterator it=lst.iterator();
        int index=0;
        while (it.hasNext()){
            Unidad uni = (Unidad)it.next();
            if (uni.getCodigo()==uniParam.getCodigo()){
                return index;
            }
            index++;
        }
        return -1;
            
    }
    
    public void searchCombo(JComboBox jc){   
        String st=((JTextField)jc.getEditor().getEditorComponent()).getText();
        for(int i=0;i<jc.getModel().getSize();i++)
        {
           if(((String)jc.getItemAt(i)).contains(st)){
           jc.setSelectedIndex(i); 
           ((JTextField)jc.getEditor().getEditorComponent()).setText((String)jc.getSelectedItem());
           }
                  
        }
   }
    private boolean validateFields()
    {
        
     
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        df.setLenient(false);
        
        try {
            df.parse("01/"+this.jFtf_Periodo.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar un período válido. Ej. 01/2007 (Enero de 2007)");
            this.jFtf_Periodo.requestFocus();
            return false;  
        }
        
        if(this.jTxt_Descripcion.getText().trim().length()>40){
            JOptionPane.showMessageDialog(this.getContentPane(),"La descripción no pude ser mayor a 40 caracteres");
            this.jTxt_Descripcion.requestFocus();
            return false;
        }
        
        try {
            Double.parseDouble(this.jTxt_Monto.getText());
        } catch(Exception e){
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar un importe válido");
            this.jTxt_Monto.requestFocus();
            return false;    
        }
        
        if (this.jCmb_Consorcio_Hasta.getSelectedIndex()==-1){
          JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar un Consorcio al cual transferir el gasto");
          this.jCmb_Consorcio_Hasta.requestFocus();
          return false;  
        }
        if (!this.getGiUpdated().getConcepto().getCoeficiente().isDistribuible()){
            if (this.jCmb_Unidad_Hasta.getSelectedIndex()==-1){
                JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar una Unidad a la cual transferir el gasto");
                this.jCmb_Unidad_Hasta.requestFocus();
                return false;  
            }
        }
        
        return true;
    }

    public GastoImputado getGiUpdated() {
        return giUpdated;
    }

    public void setGiUpdated(GastoImputado giUpdated) {
        this.giUpdated = giUpdated;
    }

    public ConsultaGastosNoImp getCci() {
        return cci;
    }

    public void setCci(ConsultaGastosNoImp cci) {
        this.cci = cci;
    }


}
