/*
 * ComprobantesGastos.java
 *
 * Created on 21 de diciembre de 2007, 20:57
 */

package expensav20.GUI;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ListDataListener;
import javax.swing.text.MaskFormatter;
import model.Concepto;
import model.Consorcio;
import model.GastoImputado;
import model.Unidad;

/**
 *
 * @author  Javier
 */
public class ComprobantesGastos extends javax.swing.JFrame {
    
    /** Creates new form ComprobantesGastos */
    public ComprobantesGastos() {
        initComponents();
        this.buttonGroup1.add(this.jRdb_Unidad);
        this.buttonGroup1.add(this.jRdb_consorcio);
        this.jCmb_Consorcio.setModel(new ComboConsorciosModel());
        this.jCmb_Unidad.setModel(new ComboUnidadesModel());
        this.jCmb_Consorcio.setEditable(true);
        this.jCmb_Unidad.setEditable(true);
        this.jCmb_Consorcio.updateUI();
        this.jCmb_Unidad.updateUI();
        this.jCmb_Gasto.setModel(new ComboConceptosModel());
        this.jCmb_Gasto.updateUI();
         try {
            MaskFormatter mascara_fecha = new MaskFormatter("##/##/####");
            MaskFormatter mascara_periodo = new MaskFormatter("##/####");
            MaskFormatter mascara_periodoGasto = new MaskFormatter("##/####");
            mascara_fecha.install(this.jFtf_Fecha);
            mascara_periodo.install(this.jFtf_Periodo);
            mascara_periodoGasto.install(this.jFtf_PeriodoGasto);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jCmb_Gasto = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxt_Comprobante = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxt_Descripcion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jRdb_Unidad = new javax.swing.JRadioButton();
        jRdb_consorcio = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCmb_Consorcio = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jCmb_Unidad = new javax.swing.JComboBox();
        jBtn_Consultar = new javax.swing.JButton();
        jBtn_Popular = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxt_Consorcio = new javax.swing.JTextField();
        jTxt_Unidad = new javax.swing.JTextField();
        jTxt_Propietario = new javax.swing.JTextField();
        jFtf_Importe = new javax.swing.JFormattedTextField();
        jFtf_Periodo = new javax.swing.JFormattedTextField();
        jFtf_Fecha = new javax.swing.JFormattedTextField();
        jFtf_PeriodoGasto = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jBtn_Salir = new javax.swing.JButton();
        jBtn_Cancelar = new javax.swing.JButton();
        jBtn_Aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de Gastos");
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gastos"));
        jLabel4.setText("Concepto:");

        jCmb_Gasto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aguas Cordobesas" }));
        jCmb_Gasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_GastoActionPerformed(evt);
            }
        });
        jCmb_Gasto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCmb_GastoFocusLost(evt);
            }
        });

        jLabel5.setText("Fecha:");

        jLabel6.setText("Importe:");

        jLabel7.setText("Nro. Comp.:");

        jLabel8.setText("Per\u00edodo a Liq.:");

        jLabel10.setText("Descripci\u00f3n:");

        jTxt_Descripcion.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Gasto de:"));
        jRdb_Unidad.setText("Unidad");
        jRdb_Unidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRdb_Unidad.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRdb_Unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdb_UnidadActionPerformed(evt);
            }
        });

        jRdb_consorcio.setText("Consorcio");
        jRdb_consorcio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRdb_consorcio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRdb_consorcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdb_consorcioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRdb_Unidad)
                    .addComponent(jRdb_consorcio)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jRdb_Unidad)
                .addGap(15, 15, 15)
                .addComponent(jRdb_consorcio))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setText("Consorcio:");

        jCmb_Consorcio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Art\u00edculo 1", "Art\u00edculo 2", "Art\u00edculo 3", "Art\u00edculo 4" }));
        jCmb_Consorcio.setEnabled(false);
        jCmb_Consorcio.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_ConsorcioPopupMenuWillBecomeVisible(evt);
            }
        });
        jCmb_Consorcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_ConsorcioActionPerformed(evt);
            }
        });

        jLabel2.setText("Unidad:");

        jCmb_Unidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Art\u00edculo 1", "Art\u00edculo 2", "Art\u00edculo 3", "Art\u00edculo 4" }));
        jCmb_Unidad.setEnabled(false);
        jCmb_Unidad.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_UnidadPopupMenuWillBecomeVisible(evt);
            }
        });
        jCmb_Unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_UnidadActionPerformed(evt);
            }
        });

        jBtn_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/zoom.png")));
        jBtn_Consultar.setText("Consultar");
        jBtn_Consultar.setEnabled(false);
        jBtn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ConsultarActionPerformed(evt);
            }
        });

        jBtn_Popular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/hourglass_add.png")));
        jBtn_Popular.setEnabled(false);
        jBtn_Popular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_PopularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCmb_Consorcio, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmb_Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtn_Consultar)
                    .addComponent(jBtn_Popular, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jCmb_Consorcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtn_Popular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jCmb_Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtn_Consultar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.setText("Consorcio:");

        jLabel9.setText("Unidad:");

        jLabel11.setText("Propietario:");

        jTxt_Consorcio.setEditable(false);

        jTxt_Unidad.setEditable(false);

        jTxt_Propietario.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTxt_Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxt_Propietario))
                    .addComponent(jTxt_Consorcio, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_Consorcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTxt_Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel12.setText("Per\u00edodo Gasto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jFtf_Importe, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxt_Comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCmb_Gasto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFtf_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFtf_PeriodoGasto)
                                    .addComponent(jFtf_Periodo, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                            .addComponent(jTxt_Descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFtf_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jFtf_Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCmb_Gasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jFtf_PeriodoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxt_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFtf_Importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_Comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jBtn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/door_out.png")));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        jBtn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/cross.png")));
        jBtn_Cancelar.setText("Cancelar");
        jBtn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CancelarActionPerformed(evt);
            }
        });

        jBtn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/tick.png")));
        jBtn_Aceptar.setText("Aceptar");
        jBtn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtn_Aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Salir)
                    .addComponent(jBtn_Cancelar)
                    .addComponent(jBtn_Aceptar))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmb_GastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_GastoActionPerformed
        if ((this.jCmb_Gasto.getSelectedIndex()!=-1) && ((Concepto)((ComboConceptosModel)this.jCmb_Gasto.getModel()).getLst().get(this.jCmb_Gasto.getSelectedIndex())).isDescripcion()==true){
            this.jTxt_Descripcion.setEnabled(true);
        }
        else{
            this.jTxt_Descripcion.setEnabled(false);
        }
    }//GEN-LAST:event_jCmb_GastoActionPerformed

    private void jCmb_GastoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCmb_GastoFocusLost
        if ((this.jCmb_Gasto.getSelectedIndex()!=-1) && ((Concepto)((ComboConceptosModel)this.jCmb_Gasto.getModel()).getLst().get(this.jCmb_Gasto.getSelectedIndex())).isDescripcion()==true){
            this.jTxt_Descripcion.setEnabled(true);
        }
        else{
            this.jTxt_Descripcion.setEnabled(false);
        }
    }//GEN-LAST:event_jCmb_GastoFocusLost

    private void jBtn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ConsultarActionPerformed

        if (this.jCmb_Consorcio.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar un Consorcio");
            this.jCmb_Consorcio.requestFocus();
            return;
        }
        if (this.jRdb_Unidad.isSelected()){
            if (this.jCmb_Unidad.getSelectedIndex()==-1){
                JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar una unidad");
                this.jCmb_Unidad.requestFocus();
                return;
            }
            Unidad uni =(Unidad) ((ComboUnidadesModel)this.jCmb_Unidad.getModel()).getLst().get(this.jCmb_Unidad.getSelectedIndex());
            this.jTxt_Consorcio.setText(uni.getConsorcio().getDenominacion());
            this.jTxt_Propietario.setText(uni.getPropietario().getNombre());
            this.jTxt_Unidad.setText(uni.getDescripcion());
        }
        else{
            Consorcio con = (Consorcio)((ComboConsorciosModel)this.jCmb_Consorcio.getModel()).getLst().get(this.jCmb_Consorcio.getSelectedIndex());
            this.jTxt_Consorcio.setText(con.getDenominacion());
        }
    }//GEN-LAST:event_jBtn_ConsultarActionPerformed

    private void jCmb_UnidadPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_UnidadPopupMenuWillBecomeVisible
        this.searchCombo(this.jCmb_Unidad);
    }//GEN-LAST:event_jCmb_UnidadPopupMenuWillBecomeVisible

    private void jCmb_ConsorcioPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioPopupMenuWillBecomeVisible
        this.searchCombo(this.jCmb_Consorcio);
    }//GEN-LAST:event_jCmb_ConsorcioPopupMenuWillBecomeVisible

    private void jCmb_UnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_UnidadActionPerformed
                ((JTextField)this.jCmb_Unidad.getEditor().getEditorComponent()).setText(((String)this.jCmb_Unidad.getSelectedItem()));        
    }//GEN-LAST:event_jCmb_UnidadActionPerformed

    private void jCmb_ConsorcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioActionPerformed
        ((JTextField)this.jCmb_Consorcio.getEditor().getEditorComponent()).setText(((String)this.jCmb_Consorcio.getSelectedItem()));        
    }//GEN-LAST:event_jCmb_ConsorcioActionPerformed

    private void jBtn_PopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_PopularActionPerformed
        Consorcio cons=new Consorcio();
        if (this.jCmb_Consorcio.getSelectedIndex()!=-1){
            cons=(Consorcio)((ComboConsorciosModel)this.jCmb_Consorcio.getModel()).getLst().get(this.jCmb_Consorcio.getSelectedIndex());
            Unidad uni=new Unidad();
            ((ComboUnidadesModel)this.jCmb_Unidad.getModel()).setLst(uni.buscarxConsorcioActivas(cons));
            this.jCmb_Unidad.setSelectedIndex(-1);
            this.jCmb_Unidad.updateUI();
        }
        
    }//GEN-LAST:event_jBtn_PopularActionPerformed

    private void jRdb_consorcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdb_consorcioActionPerformed
        if(this.jRdb_consorcio.isSelected()==true){
            this.jCmb_Consorcio.setEnabled(true);
            this.jCmb_Unidad.setEnabled(false);
            this.jCmb_Consorcio.setSelectedIndex(-1);
            this.jCmb_Unidad.setSelectedIndex(-1);
            this.jBtn_Consultar.setEnabled(true);
            this.jBtn_Popular.setEnabled(false);
            this.limpiarDatosPropietario();
            Concepto con=new Concepto();
            ((ComboConceptosModel)this.jCmb_Gasto.getModel()).setLst(con.buscarVigentesxTipoSinExpensa(true,"Debe"));
            this.jCmb_Gasto.updateUI();
            this.jCmb_Gasto.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jRdb_consorcioActionPerformed

    private void jRdb_UnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdb_UnidadActionPerformed
        if (this.jRdb_Unidad.isSelected()==true){
            this.jCmb_Consorcio.setEnabled(true);
            this.jCmb_Unidad.setEnabled(true);
            this.jCmb_Consorcio.setSelectedIndex(-1);
            this.jCmb_Unidad.setSelectedIndex(-1);
            this.jBtn_Popular.setEnabled(true);
            this.jBtn_Consultar.setEnabled(true);
            this.limpiarDatosPropietario();
            Concepto con=new Concepto();
            ((ComboConceptosModel)this.jCmb_Gasto.getModel()).setLst(con.buscarVigentesxTipo(false,"Debe"));
            this.jCmb_Gasto.updateUI();
            this.jCmb_Gasto.setSelectedIndex(-1);
            
        }
    }//GEN-LAST:event_jRdb_UnidadActionPerformed

    private void jBtn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AceptarActionPerformed
        if (this.validateFields()==false)
            return;
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        GastoImputado gi=new GastoImputado();
        gi.setComprobante(this.jTxt_Comprobante.getText());
        gi.setConcepto((Concepto)((ComboConceptosModel)this.jCmb_Gasto.getModel()).getLst().get(this.jCmb_Gasto.getSelectedIndex()));
        gi.setConsorcio((Consorcio)((ComboConsorciosModel)this.jCmb_Consorcio.getModel()).getLst().get(this.jCmb_Consorcio.getSelectedIndex()));
        gi.setDescripcion(this.jTxt_Descripcion.getText());
        try {
            gi.setFecha(df.parse(this.jFtf_Fecha.getText()));
            gi.setPeriodo(df.parse("01/"+this.jFtf_Periodo.getText()));
            gi.setPeriodoGasto(df.parse("01/"+this.jFtf_PeriodoGasto.getText()));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        gi.setImporte(Double.valueOf(this.jFtf_Importe.getText()));
       
        if (this.jRdb_Unidad.isSelected()==true){
            gi.setUnidad((Unidad)((ComboUnidadesModel)this.jCmb_Unidad.getModel()).getLst().get(this.jCmb_Unidad.getSelectedIndex()));
        }        
        gi.guardar();
        if (gi.getCodigo()!=0){
            JOptionPane.showMessageDialog(this.getContentPane(),"El gasto se guardó correctamente");
            this.limpiar(false);
            this.jCmb_Unidad.requestFocus();
        }
    }//GEN-LAST:event_jBtn_AceptarActionPerformed

    private void jBtn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CancelarActionPerformed
        this.limpiar(true);
    }//GEN-LAST:event_jBtn_CancelarActionPerformed

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtn_SalirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprobantesGastos().setVisible(true);
            }
        });
    }
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtn_Aceptar;
    private javax.swing.JButton jBtn_Cancelar;
    private javax.swing.JButton jBtn_Consultar;
    private javax.swing.JButton jBtn_Popular;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JComboBox jCmb_Consorcio;
    private javax.swing.JComboBox jCmb_Gasto;
    private javax.swing.JComboBox jCmb_Unidad;
    private javax.swing.JFormattedTextField jFtf_Fecha;
    private javax.swing.JFormattedTextField jFtf_Importe;
    private javax.swing.JFormattedTextField jFtf_Periodo;
    private javax.swing.JFormattedTextField jFtf_PeriodoGasto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRdb_Unidad;
    private javax.swing.JRadioButton jRdb_consorcio;
    private javax.swing.JTextField jTxt_Comprobante;
    private javax.swing.JTextField jTxt_Consorcio;
    private javax.swing.JTextField jTxt_Descripcion;
    private javax.swing.JTextField jTxt_Propietario;
    private javax.swing.JTextField jTxt_Unidad;
    // Fin de declaración de variables//GEN-END:variables
    
    private void limpiarDatosPropietario(){
        this.jTxt_Consorcio.setText("");
        this.jTxt_Propietario.setText("");
        this.jTxt_Unidad.setText("");
    }
    
    class ComboConsorciosModel implements ComboBoxModel{
        
        Consorcio cons=new Consorcio();
        protected Object selected;
        private List lst;
         
        ComboConsorciosModel(){
            this.setLst(cons.buscarActivos());
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
            Consorcio consor=new Consorcio();
            consor=(Consorcio)getLst().get(index);
            return consor.getDenominacion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    
    class ComboUnidadesModel implements ComboBoxModel{
        
        Unidad uni=new Unidad();
        protected Object selected;
        private List lst;
         
        ComboUnidadesModel(){
            lst=new ArrayList();
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Unidad uni=new Unidad();
                uni=(Unidad)getLst().get(index);
		return uni.getConsorcio().getDenominacion() + "-" + uni.getDescripcion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    
    class ComboConceptosModel implements ComboBoxModel{
        
        Concepto conc=new Concepto();
        protected Object selected;
        private List lst=new ArrayList();
         
        ComboConceptosModel(){
            
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
            Concepto conc=new Concepto();
            conc=(Concepto)getLst().get(index);
            return conc.getNombre();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    
    public void searchCombo(JComboBox jc){   
        String st=((JTextField)jc.getEditor().getEditorComponent()).getText();
        for(int i=0;i<jc.getModel().getSize();i++)
        {
           if(((String)jc.getItemAt(i)).contains(st)){
           jc.setSelectedIndex(i); 
           ((JTextField)jc.getEditor().getEditorComponent()).setText((String)jc.getSelectedItem());
           }
                  
        }
   }
    //Método para validar Empty Fields
    private boolean validateFields(){
 
        if (this.jTxt_Consorcio.getText().trim().length()==0){
          JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar y cargar un Consorcio");
          this.jCmb_Consorcio.requestFocus();
          return false;  
        }
        if (this.jCmb_Gasto.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar un gasto para ser cargado");
            this.jCmb_Gasto.requestFocus();
            return false;
        }
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        df.setLenient(false);
        
        try {
            df.parse(this.jFtf_Fecha.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar una fecha válida");
            this.jFtf_Fecha.requestFocus();
            return false;  
        }
        try {
            df.parse("01/"+this.jFtf_Periodo.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar un período válido. Ej. 01/2007 (Enero de 2007)");
            this.jFtf_Periodo.requestFocus();
            return false;  
        }
        try {
            df.parse("01/"+this.jFtf_PeriodoGasto.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar un período del gasto válido. Ej. 01/2007 (Enero de 2007)");
            this.jFtf_PeriodoGasto.requestFocus();
            return false;  
        }
        if(this.jTxt_Descripcion.getText().trim().length()>40){
            JOptionPane.showMessageDialog(this.getContentPane(),"La descripción no pude ser mayor a 40 caracteres");
            this.jTxt_Descripcion.requestFocus();
            return false;
        }
        try {
            Double.parseDouble(this.jFtf_Importe.getText());
        } catch(Exception e){
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar un importe válido");
            this.jFtf_Importe.requestFocus();
            return false;    
        }
        if(this.jTxt_Comprobante.getText().trim().length()>30){
            JOptionPane.showMessageDialog(this.getContentPane(),"El número de comprobante no pude ser mayor a 30 caracteres");
            this.jTxt_Comprobante.requestFocus();
            return false;
        }
        
        return true;
    }
    public void limpiar(boolean todo){
        this.jTxt_Descripcion.setText("");
        this.jFtf_Importe.setText("");
        this.jTxt_Comprobante.setText("");
        if (todo==true){
            this.jRdb_Unidad.setSelected(false);
            this.jRdb_consorcio.setSelected(false);
            this.jCmb_Consorcio.setSelectedIndex(-1);
            this.jCmb_Gasto.setSelectedIndex(-1);
            this.jCmb_Unidad.setSelectedIndex(-1);
            this.jTxt_Consorcio.setText("");
            this.jTxt_Propietario.setText("");
            this.jTxt_Unidad.setText("");
            this.jFtf_Periodo.setText("");
        }
    }
}
