/*
 * ConsultaGastosNoImp.java
 *
 * Created on 4 de enero de 2008, 19:52
 */

package expensav20.GUI;

import Security.Security;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.ComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListDataListener;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;
import model.Coeficiente;
import model.Concepto;
import model.Consorcio;
import model.GastoImputado;
import model.Unidad;

/**
 *
 * @author  Javier
 */
public class ConsultaGastosNoImp extends javax.swing.JFrame implements Security{
    
    /** Creates new form ConsultaGastosNoImp */
    public ConsultaGastosNoImp() {
        initComponents();
        this.jCmb_Consorcio.setModel(new ComboConsorciosModel());
        this.jCmb_Unidad.setModel(new ComboUnidadesModel());
        this.jCmb_Concepto.setModel(new ComboConceptosModel());
        this.jCmb_Coeficiente.setModel(new ComboCoeficientesModel());
        this.jCmb_Consorcio.updateUI();
        this.jCmb_Unidad.updateUI();
        this.jCmb_Concepto.updateUI();
        this.jCmb_Coeficiente.updateUI();
        this.jTlb_Gastos.setModel(new TableGastosImputadosModel());
        this.jTlb_Gastos.getTableHeader().setReorderingAllowed(false);
        this.jTlb_Gastos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        sizeTable();
        this.jTlb_Gastos.updateUI();
        
        try {
            MaskFormatter mascara_periodo = new MaskFormatter("##/####");
            mascara_periodo.install(this.jFtf_Periodo);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCmb_Consorcio = new javax.swing.JComboBox();
        jCmb_Unidad = new javax.swing.JComboBox();
        jCmb_Concepto = new javax.swing.JComboBox();
        jBtn_Consultar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jFtf_Periodo = new javax.swing.JFormattedTextField();
        jBtn_Popular = new javax.swing.JButton();
        jCmb_Coeficiente = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jChk_Consorcio = new javax.swing.JCheckBox();
        jChk_Unidad = new javax.swing.JCheckBox();
        jChk_Concepto = new javax.swing.JCheckBox();
        jChk_Periodo = new javax.swing.JCheckBox();
        jChk_Coeficiente = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTlb_Gastos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTxt_Total = new javax.swing.JTextField();
        jBtn_Salir = new javax.swing.JButton();
        jBtn_Transferir = new javax.swing.JButton();
        jBtn_Eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Gastos");
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gastos"));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setText("Consorcio:");

        jLabel2.setText("Unidad:");

        jLabel3.setText("Concepto:");

        jCmb_Consorcio.setEditable(true);
        jCmb_Consorcio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Art\u00edculo 1", "Art\u00edculo 2", "Art\u00edculo 3", "Art\u00edculo 4" }));
        jCmb_Consorcio.setEnabled(false);
        jCmb_Consorcio.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_ConsorcioPopupMenuWillBecomeVisible(evt);
            }
        });
        jCmb_Consorcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_ConsorcioActionPerformed(evt);
            }
        });

        jCmb_Unidad.setEditable(true);
        jCmb_Unidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Art\u00edculo 1", "Art\u00edculo 2", "Art\u00edculo 3", "Art\u00edculo 4" }));
        jCmb_Unidad.setEnabled(false);
        jCmb_Unidad.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_UnidadPopupMenuWillBecomeVisible(evt);
            }
        });
        jCmb_Unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_UnidadActionPerformed(evt);
            }
        });

        jCmb_Concepto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Art\u00edculo 1", "Art\u00edculo 2", "Art\u00edculo 3", "Art\u00edculo 4" }));
        jCmb_Concepto.setEnabled(false);

        jBtn_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/zoom.png")));
        jBtn_Consultar.setText("Consultar");
        jBtn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ConsultarActionPerformed(evt);
            }
        });

        jLabel5.setText("Periodo:");

        jFtf_Periodo.setEnabled(false);

        jBtn_Popular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/hourglass_add.png")));
        jBtn_Popular.setEnabled(false);
        jBtn_Popular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_PopularActionPerformed(evt);
            }
        });

        jCmb_Coeficiente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Coeficiente A", "Coeficiente B", "Coeficiente C" }));
        jCmb_Coeficiente.setEnabled(false);
        jCmb_Coeficiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_CoeficienteActionPerformed(evt);
            }
        });
        jCmb_Coeficiente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCmb_CoeficienteFocusLost(evt);
            }
        });

        jLabel6.setText("Coeficiente:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCmb_Unidad, 0, 290, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jCmb_Coeficiente, 0, 166, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFtf_Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCmb_Concepto, 0, 290, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jCmb_Consorcio, 0, 289, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtn_Consultar)
                    .addComponent(jBtn_Popular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtn_Popular)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCmb_Consorcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jCmb_Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jCmb_Concepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jBtn_Consultar)
                    .addComponent(jFtf_Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCmb_Coeficiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jChk_Consorcio.setText("Consorcio");
        jChk_Consorcio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jChk_Consorcio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jChk_Consorcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChk_ConsorcioActionPerformed(evt);
            }
        });

        jChk_Unidad.setText("Unidad");
        jChk_Unidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jChk_Unidad.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jChk_Unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChk_UnidadActionPerformed(evt);
            }
        });

        jChk_Concepto.setText("Concepto");
        jChk_Concepto.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jChk_Concepto.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jChk_Concepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChk_ConceptoActionPerformed(evt);
            }
        });

        jChk_Periodo.setText("Periodo");
        jChk_Periodo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jChk_Periodo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jChk_Periodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChk_PeriodoActionPerformed(evt);
            }
        });

        jChk_Coeficiente.setText("Coeficiente");
        jChk_Coeficiente.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jChk_Coeficiente.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jChk_Coeficiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChk_CoeficienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChk_Periodo)
                    .addComponent(jChk_Coeficiente)
                    .addComponent(jChk_Concepto)
                    .addComponent(jChk_Unidad)
                    .addComponent(jChk_Consorcio))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jChk_Concepto, jChk_Consorcio, jChk_Periodo, jChk_Unidad});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jChk_Consorcio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChk_Unidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChk_Concepto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChk_Coeficiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChk_Periodo)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Gastos Inputados"));
        jTlb_Gastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Nro. Comprobante", "Concepto", "Importe", "Tipo Gasto"
            }
        ));
        jScrollPane2.setViewportView(jTlb_Gastos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Total:");

        jTxt_Total.setFont(new java.awt.Font("Book Antiqua", 1, 14));
        jTxt_Total.setDisabledTextColor(new java.awt.Color(255, 0, 102));
        jTxt_Total.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(jTxt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jBtn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/door_out.png")));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        jBtn_Transferir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/page_white_gear.png")));
        jBtn_Transferir.setText("Transferir");
        jBtn_Transferir.setName("jBtn_Transferir");
        jBtn_Transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_TransferirActionPerformed(evt);
            }
        });

        jBtn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/page_white_delete.png")));
        jBtn_Eliminar.setText("Eliminar");
        jBtn_Eliminar.setName("jBtn_Eliminar");
        jBtn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtn_Transferir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Salir)
                    .addComponent(jBtn_Eliminar)
                    .addComponent(jBtn_Transferir))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmb_CoeficienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCmb_CoeficienteFocusLost
    }//GEN-LAST:event_jCmb_CoeficienteFocusLost

    private void jCmb_CoeficienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_CoeficienteActionPerformed

    }//GEN-LAST:event_jCmb_CoeficienteActionPerformed

    private void jChk_CoeficienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChk_CoeficienteActionPerformed
         if(this.jChk_Coeficiente.isSelected()){
            this.jCmb_Coeficiente.setEnabled(true);
            this.jCmb_Coeficiente.requestFocus();
        }
        else{
            this.jCmb_Coeficiente.setSelectedIndex(-1);
            this.jCmb_Coeficiente.setEnabled(false);
        }
    }//GEN-LAST:event_jChk_CoeficienteActionPerformed

    private void jBtn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EliminarActionPerformed
        if (this.jTlb_Gastos.getSelectedRow()==-1){
           JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar un gasto previamente");
           return;
        }
        if(JOptionPane.showConfirmDialog(this.getContentPane(),"Está seguro que desea eliminar el gasto?")==JOptionPane.YES_OPTION){
            GastoImputado gas=(GastoImputado)((TableGastosImputadosModel)this.jTlb_Gastos.getModel()).getLst().get(this.jTlb_Gastos.getSelectedRow());
            if (gas.eliminar()!=0){
                JOptionPane.showMessageDialog(this.getContentPane(),"El gasto fue eliminado correctamente");
                this.actualizar();
            }
            else{
                JOptionPane.showMessageDialog(this.getContentPane(),"Ocurrió un problema, por favor intente nuevamente");
            }
        }
    }//GEN-LAST:event_jBtn_EliminarActionPerformed

    private void jBtn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ConsultarActionPerformed
        if (!this.validateEmptyFields())
            return;
        GastoImputado gi=new GastoImputado();
        Consorcio cons=null;
        Unidad uni=null;
        Concepto conc=null;
        Date periodo=null;
        Coeficiente coe=null;
        this.jTxt_Total.setText("0");
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        if (this.jChk_Concepto.isSelected()){
            conc=(Concepto)((ComboConceptosModel)this.jCmb_Concepto.getModel()).getLst().get(this.jCmb_Concepto.getSelectedIndex());
        }
        if (this.jChk_Consorcio.isSelected()){
            cons=(Consorcio)((ComboConsorciosModel)this.jCmb_Consorcio.getModel()).getLst().get(this.jCmb_Consorcio.getSelectedIndex());
        }
        if(this.jChk_Periodo.isSelected()){
            
            try {
                periodo = df.parse("01/"+this.jFtf_Periodo.getText());
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
        }
        if(this.jChk_Unidad.isSelected()){
            uni=(Unidad)((ComboUnidadesModel)this.jCmb_Unidad.getModel()).getLst().get(this.jCmb_Unidad.getSelectedIndex());
        }
        if(this.jChk_Coeficiente.isSelected()){
            coe=(Coeficiente)((ComboCoeficientesModel)this.jCmb_Coeficiente.getModel()).getLst().get(this.jCmb_Coeficiente.getSelectedIndex());
        }
        
       ((TableGastosImputadosModel)this.jTlb_Gastos.getModel()).setLst(gi.buscar(cons,uni,conc,periodo,coe));
        this.jTlb_Gastos.updateUI();
    }//GEN-LAST:event_jBtn_ConsultarActionPerformed

    private void jBtn_PopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_PopularActionPerformed
        Consorcio cons=new Consorcio();
        if (this.jCmb_Consorcio.getSelectedIndex()!=-1){
            cons=(Consorcio)((ComboConsorciosModel)this.jCmb_Consorcio.getModel()).getLst().get(this.jCmb_Consorcio.getSelectedIndex());
            Unidad uni=new Unidad();
            ((ComboUnidadesModel)this.jCmb_Unidad.getModel()).setLst(uni.buscarxConsorcioActivas(cons));
            this.jCmb_Unidad.setSelectedIndex(-1);
            this.jCmb_Unidad.updateUI();
        }
    }//GEN-LAST:event_jBtn_PopularActionPerformed

    private void jCmb_UnidadPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_UnidadPopupMenuWillBecomeVisible
        this.searchCombo(this.jCmb_Unidad);
    }//GEN-LAST:event_jCmb_UnidadPopupMenuWillBecomeVisible

    private void jCmb_ConsorcioPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioPopupMenuWillBecomeVisible
        this.searchCombo(this.jCmb_Consorcio);
    }//GEN-LAST:event_jCmb_ConsorcioPopupMenuWillBecomeVisible

    private void jCmb_UnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_UnidadActionPerformed
       ((JTextField)this.jCmb_Unidad.getEditor().getEditorComponent()).setText(((String)this.jCmb_Unidad.getSelectedItem()));        
    }//GEN-LAST:event_jCmb_UnidadActionPerformed

    private void jCmb_ConsorcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioActionPerformed
        ((JTextField)this.jCmb_Consorcio.getEditor().getEditorComponent()).setText(((String)this.jCmb_Consorcio.getSelectedItem()));        
    }//GEN-LAST:event_jCmb_ConsorcioActionPerformed

    private void jChk_PeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChk_PeriodoActionPerformed
        if(this.jChk_Periodo.isSelected()){
            this.jFtf_Periodo.setEnabled(true);
            this.jFtf_Periodo.requestFocus();
        }
        else{
            this.jFtf_Periodo.setText("");
            this.jFtf_Periodo.setEnabled(false);
        }
    }//GEN-LAST:event_jChk_PeriodoActionPerformed

    private void jChk_ConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChk_ConceptoActionPerformed
        if(this.jChk_Concepto.isSelected()){
            this.jCmb_Concepto.setEnabled(true);
            this.jCmb_Concepto.requestFocus();
        }
        else{
            this.jCmb_Concepto.setSelectedIndex(-1);
            this.jCmb_Concepto.setEnabled(false);
        }
    }//GEN-LAST:event_jChk_ConceptoActionPerformed

    private void jChk_UnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChk_UnidadActionPerformed
        if(this.jChk_Unidad.isSelected()){
            this.jCmb_Unidad.setEnabled(true);
            this.jCmb_Consorcio.setEnabled(true);
            this.jBtn_Popular.setEnabled(true);
            this.jCmb_Consorcio.requestFocus();
        }
        else{
            this.jCmb_Unidad.setSelectedIndex(-1);
            this.jCmb_Unidad.setEnabled(false);
            this.jBtn_Popular.setEnabled(false);
            if(!this.jChk_Consorcio.isSelected()){
                this.jCmb_Consorcio.setSelectedIndex(-1);
                this.jCmb_Consorcio.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jChk_UnidadActionPerformed

    private void jChk_ConsorcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChk_ConsorcioActionPerformed
        if(this.jChk_Consorcio.isSelected()){
            this.jCmb_Consorcio.setEnabled(true);
            this.jCmb_Consorcio.requestFocus();
        }
        else{
            this.jCmb_Consorcio.setSelectedIndex(-1);
            this.jCmb_Consorcio.setEnabled(false);
        }
    }//GEN-LAST:event_jChk_ConsorcioActionPerformed

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtn_SalirActionPerformed

    private void jBtn_TransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_TransferirActionPerformed
        if (this.jTlb_Gastos.getSelectedRow()==-1){
           JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar un gasto previamente");
           return;
        }
        GastoImputado gas=(GastoImputado)((TableGastosImputadosModel)this.jTlb_Gastos.getModel()).getLst().get(this.jTlb_Gastos.getSelectedRow());
        AltaTransferencia at = new AltaTransferencia(gas,this);
        at.setVisible(true);
    }//GEN-LAST:event_jBtn_TransferirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaGastosNoImp().setVisible(true);
            }
        });
    }
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Consultar;
    private javax.swing.JButton jBtn_Eliminar;
    private javax.swing.JButton jBtn_Popular;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JButton jBtn_Transferir;
    private javax.swing.JCheckBox jChk_Coeficiente;
    private javax.swing.JCheckBox jChk_Concepto;
    private javax.swing.JCheckBox jChk_Consorcio;
    private javax.swing.JCheckBox jChk_Periodo;
    private javax.swing.JCheckBox jChk_Unidad;
    private javax.swing.JComboBox jCmb_Coeficiente;
    private javax.swing.JComboBox jCmb_Concepto;
    private javax.swing.JComboBox jCmb_Consorcio;
    private javax.swing.JComboBox jCmb_Unidad;
    private javax.swing.JFormattedTextField jFtf_Periodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTlb_Gastos;
    private javax.swing.JTextField jTxt_Total;
    // Fin de declaración de variables//GEN-END:variables
    
   class ComboConsorciosModel implements ComboBoxModel{
        
        Consorcio cons=new Consorcio();
        protected Object selected;
        private List lst;
         
        ComboConsorciosModel(){
            this.setLst(cons.buscarActivos());
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Consorcio consor=new Consorcio();
                consor=(Consorcio)getLst().get(index);
		return consor.getDenominacion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    
    class ComboUnidadesModel implements ComboBoxModel{
        
        Unidad uni=new Unidad();
        protected Object selected;
        private List lst;
         
        ComboUnidadesModel(){
            lst=new ArrayList();
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Unidad uni=new Unidad();
                uni=(Unidad)getLst().get(index);
		return uni.getConsorcio().getDenominacion() + "-" + uni.getDescripcion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    
     class ComboConceptosModel implements ComboBoxModel{
        
        Concepto conc=new Concepto();
        protected Object selected;
        private List lst=new ArrayList();
         
        ComboConceptosModel(){
            this.setLst(conc.buscarVigentes("Debe"));
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
            Concepto conc=new Concepto();
            conc=(Concepto)getLst().get(index);
            return conc.getNombre();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
     
     public void searchCombo(JComboBox jc){   
        String st=((JTextField)jc.getEditor().getEditorComponent()).getText();
        for(int i=0;i<jc.getModel().getSize();i++)
        {
           if(((String)jc.getItemAt(i)).contains(st)){
           jc.setSelectedIndex(i); 
           ((JTextField)jc.getEditor().getEditorComponent()).setText((String)jc.getSelectedItem());
           }
                  
        }
   }
     
   class TableGastosImputadosModel implements TableModel{
        
        GastoImputado gi=new GastoImputado();
        SimpleDateFormat sdf1=new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat sdf2=new SimpleDateFormat("MM/yyyy");
        protected Object selected;
        private List lst=new ArrayList();
         
        TableGastosImputadosModel(){
           
        }
        
        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }

        public int getRowCount() {
            return this.getLst().size();
        }

        public int getColumnCount() {
            return 6;
        }

        public String getColumnName(int columnIndex) {
            switch (columnIndex){
                case 0: 
                    return "Fecha";
                case 1: 
                    return "Periodo";
                case 2: 
                    return "Consorcio/Unidad";
                case 3: 
                    return "Concepto";
                case 4: 
                    return "Descripcion";
                case 5: 
                    return "Importe";
                case 6: 
                    return "Coeficiente";
            }
            return "";
        }
        
        public Class<?> getColumnClass(int columnIndex) {
            return this.getClass();
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
       

        public Object getValueAt(int rowIndex, int columnIndex) {
            this.sumar();
            Unidad uni = (Unidad)((GastoImputado)this.getLst().get(rowIndex)).getUnidad();
            String aplica;
            GastoImputado gi=(GastoImputado)this.getLst().get(rowIndex);

            String unidad=new String();
            if(uni!=null){
                unidad=uni.getConsorcio().getDenominacion()+"-"+uni.getDescripcion();
            }
            else{
                unidad=gi.getConsorcio().getDenominacion();
            }
            
            switch(columnIndex){
                case 0:
                    return sdf1.format(((GastoImputado)this.getLst().get(rowIndex)).getFecha());
                case 1: 
                    return sdf2.format(((GastoImputado)this.getLst().get(rowIndex)).getPeriodo());
                case 2: 
                    return unidad;
                case 3: 
                    return ((GastoImputado)this.getLst().get(rowIndex)).getConcepto().getNombre();
                case 4: 
                    return ((GastoImputado)this.getLst().get(rowIndex)).getDescripcion();
                case 5: 
                    return ((GastoImputado)this.getLst().get(rowIndex)).getImporte().toString();
                case 6: 
                    return gi.getConcepto().getCoeficiente().getDenominacion();
                
                
            }
            return null;
        }
        

        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
        }

        public void addTableModelListener(TableModelListener l) {
        }

        public void removeTableModelListener(TableModelListener l) {
        }
        private void sumar(){
            NumberFormat nf = null;
            nf=NumberFormat.getInstance();
            nf.setMaximumFractionDigits(5);
            Iterator i=this.getLst().iterator();
            Double suma=new Double(0);
            while (i.hasNext()){
                suma=suma+((GastoImputado)i.next()).getImporte();
            }
            jTxt_Total.setText(nf.format(suma));
        }
    }
   public boolean validateEmptyFields(){
       if(this.jChk_Consorcio.isSelected()){
           if(this.jCmb_Consorcio.getSelectedIndex()==-1){
               JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar un consorcio");
               this.jCmb_Consorcio.requestFocus();
               return false;
           }
       }
       if(this.jChk_Unidad.isSelected()){
           if(this.jCmb_Unidad.getSelectedIndex()==-1){
               JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar una unidad");
               this.jCmb_Unidad.requestFocus();
               return false;
           }
       }
       if(this.jChk_Concepto.isSelected()){
           if(this.jCmb_Concepto.getSelectedIndex()==-1){
               JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar un concepto");
               this.jCmb_Concepto.requestFocus();
               return false;
           }
       }
       if(this.jChk_Periodo.isSelected()){
           SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
           df.setLenient(false);
            try {
                df.parse("01/"+this.jFtf_Periodo.getText());
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this.getContentPane(),"Debe ingresar un período válido");
                this.jFtf_Periodo.requestFocus();
                return false;
            }
       }
       if (this.jChk_Coeficiente.isSelected()){
           if (this.jCmb_Coeficiente.getSelectedIndex()==-1){
               JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar un coeficiente");
               this.jCmb_Coeficiente.requestFocus();
               return false;
           }
       }
       return true;
   }
   
   public void sizeTable()
   {
        this.jTlb_Gastos.getColumnModel().getColumn(0).setPreferredWidth(68);
        this.jTlb_Gastos.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.jTlb_Gastos.getColumnModel().getColumn(2).setPreferredWidth(160);
        this.jTlb_Gastos.getColumnModel().getColumn(3).setPreferredWidth(174);
        this.jTlb_Gastos.getColumnModel().getColumn(4).setPreferredWidth(170);
        this.jTlb_Gastos.getColumnModel().getColumn(5).setPreferredWidth(80);
        /*
        column2 = this.jTlb_Gastos.getColumnModel().getColumn(1);
        column2.setPreferredWidth(5);
        column = this.jTlb_Gastos.getColumnModel().getColumn(2);
        column.setPreferredWidth(60);*/
   }
   public void actualizar()
   {
        if (!this.validateEmptyFields())
            return;
        GastoImputado gi=new GastoImputado();
        Consorcio cons=null;
        Unidad uni=null;
        Concepto conc=null;
        Date periodo=null;
        Coeficiente coe = null;
        this.jTxt_Total.setText("0");
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        if (this.jChk_Concepto.isSelected()){
            conc=(Concepto)((ComboConceptosModel)this.jCmb_Concepto.getModel()).getLst().get(this.jCmb_Concepto.getSelectedIndex());
        }
        if (this.jChk_Consorcio.isSelected()){
            cons=(Consorcio)((ComboConsorciosModel)this.jCmb_Consorcio.getModel()).getLst().get(this.jCmb_Consorcio.getSelectedIndex());
        }
        if(this.jChk_Periodo.isSelected()){
            
            try {
                periodo = df.parse("01/"+this.jFtf_Periodo.getText());
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
        }
        if(this.jChk_Unidad.isSelected()){
            uni=(Unidad)((ComboUnidadesModel)this.jCmb_Unidad.getModel()).getLst().get(this.jCmb_Unidad.getSelectedIndex());
        }
        if(this.jChk_Coeficiente.isSelected()){
            coe=(Coeficiente)((ComboCoeficientesModel)this.jCmb_Coeficiente.getModel()).getLst().get(this.jCmb_Coeficiente.getSelectedIndex());
        }
       ((TableGastosImputadosModel)this.jTlb_Gastos.getModel()).setLst(gi.buscar(cons,uni,conc,periodo,coe));
        this.jTlb_Gastos.updateUI();
   }
   public Map getObjectsAffected() {
        Map a=new HashMap();
        a.put(this.jBtn_Eliminar.getName(),this.jBtn_Eliminar);
        a.put(this.jBtn_Transferir.getName(),this.jBtn_Transferir);
        return a;
    }

    public String getUIName() {
        return "ConsultaGastosNoImp";
    }
    
    class ComboCoeficientesModel implements ComboBoxModel{
        
        Coeficiente coe=new Coeficiente();
        protected Object selected;
        private List lst;
         
        ComboCoeficientesModel(){
            this.setLst(coe.buscarActivos());
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Coeficiente coef=new Coeficiente();
                coef=(Coeficiente)getLst().get(index);
		return coef.getDenominacion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
        
    }

}
