/*
 * ConsultaPagos.java
 *
 * Created on 13 de marzo de 2008, 18:20
 */

package expensav20.GUI;

import Security.Security;
import informes.InformePagos;
import java.math.BigDecimal;
import java.math.MathContext;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.ComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ListDataListener;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;
import model.Consorcio;
import model.Inquilino;
import model.Pago;
import model.Propiedades;
import model.Propietario;
import model.Unidad;

/**
 *
 * @author  Javier
 */
public class ConsultaPagos extends javax.swing.JFrame implements Security {
    private Inquilino inquilino;
    private Propietario propietario;
    /** Creates new form ConsultaPagos */
    public ConsultaPagos() {
        initComponents();
        this.jCmb_Consorcio.setModel(new ComboConsorciosModel());
        this.jCmb_Unidad.setModel(new ComboUnidadesModel());
        this.jCmb_Consorcio.updateUI();
        this.jCmb_Unidad.updateUI();
        this.jTlb_CtaCte.setModel(new TablePagosModel());
        sizeTable();
        this.jTlb_CtaCte.updateUI();
        try {
            MaskFormatter mascara_fecha = new MaskFormatter("##/##/####");
            MaskFormatter mascara_fecha2 = new MaskFormatter("##/##/####");
            mascara_fecha2.install(this.jFtf_FechaDesde);
            mascara_fecha.install(this.jFtf_FechaHasta);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtn_Consultar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTxt_Propietario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxt_Inquilino = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jChk_Propietario = new javax.swing.JCheckBox();
        jChk_Unidad = new javax.swing.JCheckBox();
        jChk_Inquilino = new javax.swing.JCheckBox();
        jChk_Periodo = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCmb_Consorcio = new javax.swing.JComboBox();
        jBtn_Popular = new javax.swing.JButton();
        jCmb_Unidad = new javax.swing.JComboBox();
        jBtn_buscarPropietario = new javax.swing.JButton();
        jBtn_BuscarInquilino = new javax.swing.JButton();
        jFtf_FechaDesde = new javax.swing.JFormattedTextField();
        jFtf_FechaHasta = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTlb_CtaCte = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTxt_Saldo = new javax.swing.JTextField();
        jBtn_Salir = new javax.swing.JButton();
        jBtn_Eliminar = new javax.swing.JButton();
        jBtn_Listar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Pagos");
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagos"));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel1.setText("Consorcio:");

        jLabel2.setText("Unidad:");

        jBtn_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/zoom.png")));
        jBtn_Consultar.setText("Consultar");
        jBtn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ConsultarActionPerformed(evt);
            }
        });

        jLabel3.setText("Propietario:");

        jTxt_Propietario.setBackground(new java.awt.Color(204, 204, 204));
        jTxt_Propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_PropietarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Inquilino:");

        jTxt_Inquilino.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar por:"));
        jChk_Propietario.setText("Propietario");
        jChk_Propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChk_PropietarioActionPerformed(evt);
            }
        });

        jChk_Unidad.setText("Unidad");
        jChk_Unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChk_UnidadActionPerformed(evt);
            }
        });

        jChk_Inquilino.setText("Inquilino");
        jChk_Inquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChk_InquilinoActionPerformed(evt);
            }
        });

        jChk_Periodo.setText("Periodo");
        jChk_Periodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChk_PeriodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChk_Unidad)
                    .addComponent(jChk_Propietario)
                    .addComponent(jChk_Inquilino)
                    .addComponent(jChk_Periodo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jChk_Unidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChk_Propietario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChk_Inquilino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChk_Periodo))
        );

        jLabel6.setText("Desde:");

        jLabel7.setText("Hasta:");

        jCmb_Consorcio.setEditable(true);
        jCmb_Consorcio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Galeria Norte", "Edificio Pajas Blancas" }));
        jCmb_Consorcio.setEnabled(false);
        jCmb_Consorcio.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_ConsorcioPopupMenuWillBecomeVisible(evt);
            }
        });
        jCmb_Consorcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_ConsorcioActionPerformed(evt);
            }
        });

        jBtn_Popular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/hourglass_add.png")));
        jBtn_Popular.setEnabled(false);
        jBtn_Popular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_PopularActionPerformed(evt);
            }
        });

        jCmb_Unidad.setEditable(true);
        jCmb_Unidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Local 1", "Local 2", "Local 3" }));
        jCmb_Unidad.setEnabled(false);
        jCmb_Unidad.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCmb_UnidadPopupMenuWillBecomeVisible(evt);
            }
        });
        jCmb_Unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmb_UnidadActionPerformed(evt);
            }
        });

        jBtn_buscarPropietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/hourglass_add.png")));
        jBtn_buscarPropietario.setEnabled(false);
        jBtn_buscarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_buscarPropietarioActionPerformed(evt);
            }
        });

        jBtn_BuscarInquilino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/hourglass_add.png")));
        jBtn_BuscarInquilino.setEnabled(false);
        jBtn_BuscarInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_BuscarInquilinoActionPerformed(evt);
            }
        });

        jFtf_FechaDesde.setEnabled(false);

        jFtf_FechaHasta.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCmb_Unidad, 0, 297, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jCmb_Consorcio, 0, 261, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_Popular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxt_Inquilino, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(jTxt_Propietario, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtn_BuscarInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_buscarPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jFtf_FechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFtf_FechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCmb_Consorcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn_Popular))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCmb_Unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTxt_Propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addComponent(jBtn_buscarPropietario)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxt_Inquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(jBtn_BuscarInquilino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jFtf_FechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jBtn_Consultar)
                                .addComponent(jFtf_FechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagos"));
        jTlb_CtaCte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12/12/2007", "Alquiler", "1000", "", "1000"},
                {"13/12/2007", "Pago", null, "1000", "0"},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Concepto", "Debe", "Haber", "Saldo"
            }
        ));
        jScrollPane1.setViewportView(jTlb_CtaCte);

        jLabel5.setText("Saldo:");

        jTxt_Saldo.setBackground(new java.awt.Color(204, 204, 204));
        jTxt_Saldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxt_Saldo.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(397, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxt_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxt_Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jBtn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/door_out.png")));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        jBtn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/page_white_delete.png")));
        jBtn_Eliminar.setText("Eliminar");
        jBtn_Eliminar.setName("jBtn_Eliminar");
        jBtn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EliminarActionPerformed(evt);
            }
        });

        jBtn_Listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/report_add.png")));
        jBtn_Listar.setText("Listar");
        jBtn_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtn_Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Listar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Salir)
                    .addComponent(jBtn_Listar)
                    .addComponent(jBtn_Eliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ListarActionPerformed
        String filtro=new String();
        
        if (this.jChk_Unidad.isSelected()){
            Unidad uni=(Unidad)((ComboUnidadesModel)this.jCmb_Unidad.getModel()).getLst().get(this.jCmb_Unidad.getSelectedIndex());
            filtro=filtro+="Unidad: " + uni.getDescripcion() + " del consorcio " + uni.getConsorcio().getDenominacion() + "\n";
        }
        if (this.jChk_Propietario.isSelected()){
            filtro=filtro+="Propietario: " + this.jTxt_Propietario.getText()+"\n";
        }
        if (this.jChk_Inquilino.isSelected()){
            filtro=filtro+="Inquilino: " + this.jTxt_Inquilino.getText() + "\n";
        }
        if (this.jChk_Periodo.isSelected()){
            SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
            try {
                filtro=filtro+"Entre el dìa: " + sdf.format(sdf.parse(this.jFtf_FechaDesde.getText())) + " y el día: " + sdf.format(sdf.parse(this.jFtf_FechaHasta.getText())) + "\n";
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
        }
        Map a = new HashMap();
        a.put("filtro",filtro);
        InformePagos ip=new InformePagos();
        ip.setParameters(a);
        ip.displayReport(this.jTlb_CtaCte);
    }//GEN-LAST:event_jBtn_ListarActionPerformed

    private void jBtn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EliminarActionPerformed
        if (this.jTlb_CtaCte.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar un pago previamente");
            return;
        }
        Pago pago=(Pago)((TablePagosModel)this.jTlb_CtaCte.getModel()).getLst().get(this.jTlb_CtaCte.getSelectedRow());
        pago.popularDetallePagos();
        if(JOptionPane.showConfirmDialog(this.getContentPane(),"Está seguro que desea eliminar el pago?")==JOptionPane.YES_OPTION){
            if (pago.eliminar()){
                JOptionPane.showMessageDialog(this.getContentPane(),"El pago se ha eliminado correctamente");
            }
            else{
                JOptionPane.showMessageDialog(this.getContentPane(),"Ha ocurrido un problema, por favor intente nuevamente");
            }

        }
        Inquilino inq=null;
        Propietario prop=null;
        Unidad uni=null;
        Date fechaDesde=null;
        Date fechaHasta=null;
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        if (this.getInquilino()!=null){
            inq=this.getInquilino();
        }
        if (this.getPropietario()!=null){
            prop=this.getPropietario();
        }
        if(this.jChk_Unidad.isSelected()){
            if(this.jCmb_Unidad.getSelectedIndex()!=-1){
                uni = (Unidad)((ComboUnidadesModel)this.jCmb_Unidad.getModel()).getLst().get(this.jCmb_Unidad.getSelectedIndex());
            }
        }
        if(this.jChk_Periodo.isSelected()){
            try {
                df.setLenient(false);
                fechaDesde=df.parse(this.jFtf_FechaDesde.getText());
                fechaHasta=df.parse(this.jFtf_FechaHasta.getText());
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this.getContentPane(),"La fecha desde o fecha hasta ingresada no es una fecha válida");
                return;
            }
            
        }
        Pago pag=new Pago();
        List pagos=pag.buscarSaldoxCriteria(uni,prop,inq,fechaDesde,fechaHasta);
        ((TablePagosModel)this.jTlb_CtaCte.getModel()).setLst(pagos);
        this.jTlb_CtaCte.updateUI();
        Iterator it = pagos.iterator();
        BigDecimal bdResult=new BigDecimal(0d);
        while (it.hasNext()){
            Pago pagoIte=(Pago)it.next();
            bdResult=bdResult.add(BigDecimal.valueOf(pagoIte.getImporte().doubleValue()));
        }
        DecimalFormat nf=(DecimalFormat) DecimalFormat.getInstance(Locale.ENGLISH);
        nf.setGroupingUsed(false);
        nf.setRoundingMode(RoundingMode.HALF_UP);
        Propiedades propi=new Propiedades();
        Map props=propi.buscarTodas();
        int cant_digitos= Integer.parseInt((String) props.get("cantidad_decimales_liquidacon"));
        nf.setMaximumFractionDigits(cant_digitos);
        this.jTxt_Saldo.setText(nf.format(bdResult.doubleValue()));
    }//GEN-LAST:event_jBtn_EliminarActionPerformed

    public void dispose() {
    }

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtn_SalirActionPerformed

    private void jBtn_BuscarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_BuscarInquilinoActionPerformed
        ConsultaInquilino ci=new ConsultaInquilino(this);
        ci.setVisible(true);
    }//GEN-LAST:event_jBtn_BuscarInquilinoActionPerformed

    private void jBtn_buscarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_buscarPropietarioActionPerformed
        ConsultaPropietario cp=new ConsultaPropietario(this);
        cp.setVisible(true);
    }//GEN-LAST:event_jBtn_buscarPropietarioActionPerformed

    private void jCmb_UnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_UnidadActionPerformed
        ((JTextField)this.jCmb_Unidad.getEditor().getEditorComponent()).setText(((String)this.jCmb_Unidad.getSelectedItem()));
    }//GEN-LAST:event_jCmb_UnidadActionPerformed

    private void jCmb_UnidadPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_UnidadPopupMenuWillBecomeVisible
        this.searchCombo(this.jCmb_Unidad);
    }//GEN-LAST:event_jCmb_UnidadPopupMenuWillBecomeVisible

    private void jBtn_PopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_PopularActionPerformed
        Consorcio cons=new Consorcio();
        if (this.jCmb_Consorcio.getSelectedIndex()!=-1){
            cons=(Consorcio)((ComboConsorciosModel)this.jCmb_Consorcio.getModel()).getLst().get(this.jCmb_Consorcio.getSelectedIndex());
            Unidad uni=new Unidad();
            ((ComboUnidadesModel)this.jCmb_Unidad.getModel()).setLst(uni.buscarxConsorcioActivas(cons));
            this.jCmb_Unidad.setSelectedIndex(-1);
            this.jCmb_Unidad.updateUI();
        }
    }//GEN-LAST:event_jBtn_PopularActionPerformed

    private void jCmb_ConsorcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioActionPerformed
        ((JTextField)this.jCmb_Consorcio.getEditor().getEditorComponent()).setText(((String)this.jCmb_Consorcio.getSelectedItem()));
    }//GEN-LAST:event_jCmb_ConsorcioActionPerformed

    private void jCmb_ConsorcioPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCmb_ConsorcioPopupMenuWillBecomeVisible
        this.searchCombo(this.jCmb_Consorcio);
    }//GEN-LAST:event_jCmb_ConsorcioPopupMenuWillBecomeVisible

    private void jChk_PeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChk_PeriodoActionPerformed
        if(this.jChk_Periodo.isSelected()){
            this.jFtf_FechaDesde.setEnabled(true);
            this.jFtf_FechaHasta.setEnabled(true);
            this.jFtf_FechaDesde.requestFocus();
        } else{
            this.jFtf_FechaDesde.setText("");
            this.jFtf_FechaHasta.setText("");
            this.jFtf_FechaDesde.setEnabled(false);
            this.jFtf_FechaHasta.setEnabled(false);
        }
    }//GEN-LAST:event_jChk_PeriodoActionPerformed

    private void jChk_InquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChk_InquilinoActionPerformed
        if(this.jChk_Inquilino.isSelected()){
            this.jBtn_BuscarInquilino.setEnabled(true);
        } else{
            this.jBtn_BuscarInquilino.setEnabled(false);
            this.jTxt_Inquilino.setText("");
            this.setInquilino(null);
        }
    }//GEN-LAST:event_jChk_InquilinoActionPerformed

    private void jChk_UnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChk_UnidadActionPerformed
        if (this.jChk_Unidad.isSelected()){
            this.jCmb_Consorcio.setEnabled(true);
            this.jCmb_Unidad.setEnabled(true);
            this.jBtn_Popular.setEnabled(true);
            this.jCmb_Consorcio.requestFocus();
        } else{
            this.jCmb_Consorcio.setEnabled(false);
            this.jCmb_Unidad.setEnabled(false);
            this.jCmb_Consorcio.setSelectedIndex(-1);
            this.jCmb_Unidad.setSelectedIndex(-1);
            this.jBtn_Popular.setEnabled(false);
        }
    }//GEN-LAST:event_jChk_UnidadActionPerformed

    private void jChk_PropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChk_PropietarioActionPerformed
        if (this.jChk_Propietario.isSelected()){
            this.jBtn_buscarPropietario.setEnabled(true);
        } else{
            this.jBtn_buscarPropietario.setEnabled(false);
            this.setPropietario(null);
            this.jTxt_Propietario.setText("");
        }
    }//GEN-LAST:event_jChk_PropietarioActionPerformed

    private void jTxt_PropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_PropietarioActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jTxt_PropietarioActionPerformed

    private void jBtn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ConsultarActionPerformed
        Inquilino inq=null;
        Propietario prop=null;
        Unidad uni=null;
        Date fechaDesde=null;
        Date fechaHasta=null;
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        if (this.getInquilino()!=null){
            inq=this.getInquilino();
        }
        if (this.getPropietario()!=null){
            prop=this.getPropietario();
        }
        if(this.jChk_Unidad.isSelected()){
            if(this.jCmb_Unidad.getSelectedIndex()!=-1){
                uni = (Unidad)((ComboUnidadesModel)this.jCmb_Unidad.getModel()).getLst().get(this.jCmb_Unidad.getSelectedIndex());
            }
        }
        if(this.jChk_Periodo.isSelected()){
            try {
                df.setLenient(false);
                fechaDesde=df.parse(this.jFtf_FechaDesde.getText());
                fechaHasta=df.parse(this.jFtf_FechaHasta.getText());
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this.getContentPane(),"La fecha desde o fecha hasta ingresada no es una fecha válida");
                return;
            }
            
        }
        Pago pag=new Pago();
        List pagos=pag.buscarSaldoxCriteria(uni,prop,inq,fechaDesde,fechaHasta);
        ((TablePagosModel)this.jTlb_CtaCte.getModel()).setLst(pagos);
        this.jTlb_CtaCte.updateUI();
        Iterator it = pagos.iterator();
        BigDecimal bdResult=new BigDecimal(0d);
        while (it.hasNext()){
            Pago pagoIte=(Pago)it.next();
            bdResult=bdResult.add(BigDecimal.valueOf(pagoIte.getImporte().doubleValue()));
        }
        DecimalFormat nf=(DecimalFormat) DecimalFormat.getInstance(Locale.ENGLISH);
        nf.setGroupingUsed(false);
        nf.setRoundingMode(RoundingMode.HALF_UP);
        Propiedades propi=new Propiedades();
        Map props=propi.buscarTodas();
        //int cant_digitos= Integer.parseInt((String) props.get("cantidad_decimales_liquidacon"));
        nf.setMaximumFractionDigits(2);
        this.jTxt_Saldo.setText(nf.format(bdResult.doubleValue()));
    }//GEN-LAST:event_jBtn_ConsultarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPagos().setVisible(true);
            }
        });
    }
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_BuscarInquilino;
    private javax.swing.JButton jBtn_Consultar;
    private javax.swing.JButton jBtn_Eliminar;
    private javax.swing.JButton jBtn_Listar;
    private javax.swing.JButton jBtn_Popular;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JButton jBtn_buscarPropietario;
    private javax.swing.JCheckBox jChk_Inquilino;
    private javax.swing.JCheckBox jChk_Periodo;
    private javax.swing.JCheckBox jChk_Propietario;
    private javax.swing.JCheckBox jChk_Unidad;
    private javax.swing.JComboBox jCmb_Consorcio;
    private javax.swing.JComboBox jCmb_Unidad;
    private javax.swing.JFormattedTextField jFtf_FechaDesde;
    private javax.swing.JFormattedTextField jFtf_FechaHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTlb_CtaCte;
    private javax.swing.JTextField jTxt_Inquilino;
    private javax.swing.JTextField jTxt_Propietario;
    private javax.swing.JTextField jTxt_Saldo;
    // Fin de declaración de variables//GEN-END:variables
    public void setearPropietario(String nombre){
        this.jTxt_Propietario.setText(nombre);
    }
    public void setearInquilino(String nombre){
        this.jTxt_Inquilino.setText(nombre);
    }   

    public Inquilino getInquilino() {
        return inquilino;
    }

    public void setInquilino(Inquilino inquilino) {
        this.inquilino = inquilino;
    }

    public Propietario getPropietario() {
        return propietario;
    }

    public void setPropietario(Propietario propietario) {
        this.propietario = propietario;
    }
    
    class ComboConsorciosModel implements ComboBoxModel{
        
        Consorcio cons=new Consorcio();
        protected Object selected;
        private List lst;
         
        ComboConsorciosModel(){
            this.setLst(cons.buscarActivos());
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
            Consorcio consor=new Consorcio();
            consor=(Consorcio)getLst().get(index);
            return consor.getDenominacion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    
    class ComboUnidadesModel implements ComboBoxModel{
        
        Unidad uni=new Unidad();
        protected Object selected;
        private List lst;
         
        ComboUnidadesModel(){
            lst=new ArrayList();
        }
        public void setSelectedItem(Object item) {
               this.selected=item;
        }
	public Object getSelectedItem() {
		return this.selected;
	}

	public String getElementAt(int index) {
                Unidad uni=new Unidad();
                uni=(Unidad)getLst().get(index);
		return uni.getConsorcio().getDenominacion() + "-" + uni.getDescripcion();
	}
        
	public int getSize() {
		return getLst().size();
	}        

        public void addListDataListener(ListDataListener l) {
        }

        public void removeListDataListener(ListDataListener l) {
        }

        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }
    }
    
    
    public void searchCombo(JComboBox jc){   
        String st=((JTextField)jc.getEditor().getEditorComponent()).getText();
        for(int i=0;i<jc.getModel().getSize();i++)
        {
           if(((String)jc.getItemAt(i)).contains(st)){
           jc.setSelectedIndex(i); 
           ((JTextField)jc.getEditor().getEditorComponent()).setText((String)jc.getSelectedItem());
           }
                  
        }
   }
    
   class TablePagosModel implements TableModel{
        
        private Pago pago=new Pago();
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
        protected Object selected;
        private List lst=new ArrayList();
         
        TablePagosModel(){
           
        }
        
        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }

        public int getRowCount() {
            return this.getLst().size();
        }

        public int getColumnCount() {
            return 3;
        }

        public String getColumnName(int columnIndex) {
            switch (columnIndex){
                case 0: 
                    return "Fecha";
                case 1: 
                    return "Concepto";
                case 2: 
                    return "Importe";
              
            }
            return "";
        }
        
        public Class<?> getColumnClass(int columnIndex) {
            return this.getClass();
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
       

        public Object getValueAt(int rowIndex, int columnIndex) {
            Pago pag=(Pago)this.getLst().get(rowIndex);
            switch(columnIndex){
                case 0:
                    return sdf.format(pag.getFecha());
                case 1: 
                    return pag.getConcepto().getNombre();
                case 2: 
                    return pag.getImporte();
            }
            return null;
        }
        

        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
        }

        public void addTableModelListener(TableModelListener l) {
        }

        public void removeTableModelListener(TableModelListener l) {
        }

    }

   public Map getObjectsAffected() {
        Map a=new HashMap();
        a.put(this.jBtn_Eliminar.getName(),this.jBtn_Eliminar);
        return a;
    }

    public String getUIName() {
        return "ConsultaPagos";
    }
    
   public void sizeTable()
   {
        this.jTlb_CtaCte.getColumnModel().getColumn(0).setPreferredWidth(72);
        this.jTlb_CtaCte.getColumnModel().getColumn(1).setPreferredWidth(369);
        this.jTlb_CtaCte.getColumnModel().getColumn(2).setPreferredWidth(89);
   }
}
