/*
 * importExportDB.java
 *
 * Created on 5 de marzo de 2008, 18:06
 */

package expensav20.GUI;

import expensav20.Utilidades;
import javax.swing.JOptionPane;

/**
 *
 * @author  Javier
 */
public class ExportDB extends javax.swing.JFrame {
    
    /** Creates new form importExportDB */
    public ExportDB() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jTxt_NombreArchivo = new javax.swing.JTextField();
        jBtn_ExplorarFolders = new javax.swing.JButton();
        jBtn_ExportImport = new javax.swing.JButton();
        jBtn_Salir = new javax.swing.JButton();
        jFc_Explorar = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exportar DB");
        jLabel1.setText("Nombre del Archivo:");

        jBtn_ExplorarFolders.setText("...");
        jBtn_ExplorarFolders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ExplorarFoldersActionPerformed(evt);
            }
        });

        jBtn_ExportImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/database_save.png")));
        jBtn_ExportImport.setText("Exportar");
        jBtn_ExportImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ExportImportActionPerformed(evt);
            }
        });

        jBtn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/door_out.png")));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jFc_Explorar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_ExportImport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Salir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxt_NombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_ExplorarFolders, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxt_NombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_ExplorarFolders))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn_Salir)
                            .addComponent(jBtn_ExportImport)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFc_Explorar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_ExportImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ExportImportActionPerformed
        if(this.jTxt_NombreArchivo.getText().length()==0){
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar un directorio y un nombre de archivo primero");
            return;
        }
        Utilidades ut=new Utilidades();
        if(ut.exportarDB(this.jTxt_NombreArchivo.getText())){
            JOptionPane.showMessageDialog(this.getContentPane(),"La base de datos fue exportada correctamente");
        }
        else{
            JOptionPane.showMessageDialog(this.getContentPane(),"Ocurrió un problema, por favor intente nuevamente");
        }
       
    }//GEN-LAST:event_jBtn_ExportImportActionPerformed

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtn_SalirActionPerformed

    private void jBtn_ExplorarFoldersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ExplorarFoldersActionPerformed
        this.jFc_Explorar.setDialogType(this.jFc_Explorar.SAVE_DIALOG);
        this.jFc_Explorar.showSaveDialog(this.getContentPane());
        this.jTxt_NombreArchivo.setText(this.jFc_Explorar.getSelectedFile().getPath());
        
    }//GEN-LAST:event_jBtn_ExplorarFoldersActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportDB().setVisible(true);
            }
        });
    }
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_ExplorarFolders;
    private javax.swing.JButton jBtn_ExportImport;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JFileChooser jFc_Explorar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTxt_NombreArchivo;
    // Fin de declaración de variables//GEN-END:variables
    
}
