/*
 * Menu.java
 *
 * Created on 18 de diciembre de 2007, 21:06
 */

package expensav20.GUI;

import Security.Role;
import Security.Security;
import Security.SecurityManagerFwk;
import Security.User;
import expensav20.Utilidades;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author  Javier
 */
public class Menu extends javax.swing.JFrame implements Security {
    
    /** Creates new form Menu */
    public Menu() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);        
    }
    private static User Usuario;
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jToolBar1 = new javax.swing.JToolBar();
        jBtn_ComprobanteGastos = new javax.swing.JButton();
        jBtn_ConsultarComprobantes = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        jBtn_Liquidar = new javax.swing.JButton();
        jBtn_MostrarLiquidaciones = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JSeparator();
        jBtn_CtaCte = new javax.swing.JButton();
        jBtn_Pagos = new javax.swing.JButton();
        jBtn_ConsultarPagos = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JSeparator();
        jBtn_IG = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JSeparator();
        jBtn_Usuarios = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JSeparator();
        jBtn_Salir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMi_Consorcio = new javax.swing.JMenuItem();
        jMi_Unidades = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMi_Propietario = new javax.swing.JMenuItem();
        jMi_Inquilino = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        jMi_Coeficientes = new javax.swing.JMenuItem();
        jMi_Conceptos = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        jMi_AsignarCoeficientes = new javax.swing.JMenuItem();
        jMi_Numeros_Expensas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMi_AltaComprobantes = new javax.swing.JMenuItem();
        jMi_ConsultaComprobantes = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        jMi_ConsultaCtaCte = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JSeparator();
        jMi_AltaPagos = new javax.swing.JMenuItem();
        jMi_ConsultaPagos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMi_ConsultaConsorcio = new javax.swing.JMenuItem();
        jMi_ConsultaUnidades = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JSeparator();
        jMi_ConsultaPropietario = new javax.swing.JMenuItem();
        jMi_ConsultaInquilinos = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JSeparator();
        jMi_ConsultaCoeficientes = new javax.swing.JMenuItem();
        jMi_ConsultaConceptos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMi_ImprimirLiq = new javax.swing.JMenuItem();
        jMi_GenerarLiq = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMi_IngBrutos = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JSeparator();
        jMi_InformeAnexo = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMi_ListSaldo = new javax.swing.JMenuItem();
        jMi_ListExpComunes = new javax.swing.JMenuItem();
        jMi_ListExpensas = new javax.swing.JMenuItem();
        jMi_ListTotalConceptos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMi_Usuarios = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JSeparator();
        jMi_BackupDB = new javax.swing.JMenuItem();
        jMi_RestorDb = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JSeparator();
        jMi_Propiedades = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Men\u00fa Principal");
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);
        jBtn_ComprobanteGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/page_add.png")));
        jBtn_ComprobanteGastos.setToolTipText("Alta de Comprobantes");
        jBtn_ComprobanteGastos.setName("jBtn_ComprobanteGastos");
        jBtn_ComprobanteGastos.setPreferredSize(new java.awt.Dimension(30, 30));
        jBtn_ComprobanteGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ComprobanteGastosActionPerformed(evt);
            }
        });

        jToolBar1.add(jBtn_ComprobanteGastos);

        jBtn_ConsultarComprobantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/page_find.png")));
        jBtn_ConsultarComprobantes.setToolTipText("Consulta Comprobantes de Gastos");
        jBtn_ConsultarComprobantes.setName("jBtn_ConsultarComprobantes");
        jBtn_ConsultarComprobantes.setPreferredSize(new java.awt.Dimension(30, 30));
        jBtn_ConsultarComprobantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ConsultarComprobantesActionPerformed(evt);
            }
        });

        jToolBar1.add(jBtn_ConsultarComprobantes);

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator12.setMaximumSize(new java.awt.Dimension(1, 70));
        jSeparator12.setPreferredSize(new java.awt.Dimension(1, 0));
        jToolBar1.add(jSeparator12);

        jBtn_Liquidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/lightning_go.png")));
        jBtn_Liquidar.setToolTipText("Generar Liquidaciones");
        jBtn_Liquidar.setName("jBtn_Liquidar");
        jBtn_Liquidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_LiquidarActionPerformed(evt);
            }
        });

        jToolBar1.add(jBtn_Liquidar);

        jBtn_MostrarLiquidaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/page_white_gear.png")));
        jBtn_MostrarLiquidaciones.setToolTipText("Mostrar Liquidaciones");
        jBtn_MostrarLiquidaciones.setName("jBtn_MostrarLiquidaciones");
        jBtn_MostrarLiquidaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_MostrarLiquidacionesActionPerformed(evt);
            }
        });

        jToolBar1.add(jBtn_MostrarLiquidaciones);

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator13.setMaximumSize(new java.awt.Dimension(1, 80));
        jToolBar1.add(jSeparator13);

        jBtn_CtaCte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/application_side_list.png")));
        jBtn_CtaCte.setToolTipText("Cuenta Corriente");
        jBtn_CtaCte.setName("jBtn_CtaCte");
        jBtn_CtaCte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CtaCteActionPerformed(evt);
            }
        });

        jToolBar1.add(jBtn_CtaCte);

        jBtn_Pagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/coins_add.png")));
        jBtn_Pagos.setToolTipText("Registrar Pagos");
        jBtn_Pagos.setName("jBtn_Pagos");
        jBtn_Pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_PagosActionPerformed(evt);
            }
        });

        jToolBar1.add(jBtn_Pagos);

        jBtn_ConsultarPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/cart_go.png")));
        jBtn_ConsultarPagos.setToolTipText("Consultar Pagos");
        jBtn_ConsultarPagos.setName("jBtn_ConsultarPagos");
        jBtn_ConsultarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ConsultarPagosActionPerformed(evt);
            }
        });

        jToolBar1.add(jBtn_ConsultarPagos);

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator14.setMaximumSize(new java.awt.Dimension(1, 80));
        jToolBar1.add(jSeparator14);

        jBtn_IG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/money.png")));
        jBtn_IG.setToolTipText("Liquidar I.G.");
        jBtn_IG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtn_IG.setName("jBtn_IG");
        jBtn_IG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_IGActionPerformed(evt);
            }
        });

        jToolBar1.add(jBtn_IG);

        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator15.setMaximumSize(new java.awt.Dimension(10, 80));
        jToolBar1.add(jSeparator15);

        jBtn_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/user.png")));
        jBtn_Usuarios.setToolTipText("Administrar Usuarios");
        jBtn_Usuarios.setName("jBtn_Usuarios");
        jBtn_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_UsuariosActionPerformed(evt);
            }
        });

        jToolBar1.add(jBtn_Usuarios);

        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator16.setMaximumSize(new java.awt.Dimension(10, 80));
        jToolBar1.add(jSeparator16);

        jBtn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/house_go.png")));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        jToolBar1.add(jBtn_Salir);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("Archivo");
        jMi_Consorcio.setText("Consorcio");
        jMi_Consorcio.setName("jMi_Consorcio");
        jMi_Consorcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ConsorcioActionPerformed(evt);
            }
        });

        jMenu1.add(jMi_Consorcio);

        jMi_Unidades.setText("Unidades");
        jMi_Unidades.setName("jMi_Unidades");
        jMi_Unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_UnidadesActionPerformed(evt);
            }
        });

        jMenu1.add(jMi_Unidades);

        jMenu1.add(jSeparator2);

        jMi_Propietario.setText("Propietario");
        jMi_Propietario.setName("jMi_Propietario");
        jMi_Propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_PropietarioActionPerformed(evt);
            }
        });

        jMenu1.add(jMi_Propietario);

        jMi_Inquilino.setText("Inquilino");
        jMi_Inquilino.setName("jMi_Inquilino");
        jMi_Inquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_InquilinoActionPerformed(evt);
            }
        });

        jMenu1.add(jMi_Inquilino);

        jMenu1.add(jSeparator3);

        jMi_Coeficientes.setText("Coeficientes");
        jMi_Coeficientes.setName("jMi_Coeficientes");
        jMi_Coeficientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_CoeficientesActionPerformed(evt);
            }
        });

        jMenu1.add(jMi_Coeficientes);

        jMi_Conceptos.setText("Conceptos");
        jMi_Conceptos.setName("jMi_Conceptos");
        jMi_Conceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ConceptosActionPerformed(evt);
            }
        });

        jMenu1.add(jMi_Conceptos);

        jMenu1.add(jSeparator4);

        jMi_AsignarCoeficientes.setText("Asignar Coeficientes");
        jMi_AsignarCoeficientes.setName("jMi_AsignarCoeficientes");
        jMi_AsignarCoeficientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_AsignarCoeficientesActionPerformed(evt);
            }
        });

        jMenu1.add(jMi_AsignarCoeficientes);

        jMi_Numeros_Expensas.setText("Asignar N\u00fameros Expensas");
        jMi_Numeros_Expensas.setName("jMi_Numeros_Expensas");
        jMi_Numeros_Expensas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_Numeros_ExpensasActionPerformed(evt);
            }
        });

        jMenu1.add(jMi_Numeros_Expensas);

        jMenu1.add(jSeparator1);

        jMenuItem6.setText("Salir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cta. Cte.");
        jMi_AltaComprobantes.setLabel("Alta Comprobantes");
        jMi_AltaComprobantes.setName("jMi_AltaComprobantes");
        jMi_AltaComprobantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_AltaComprobantesActionPerformed(evt);
            }
        });

        jMenu2.add(jMi_AltaComprobantes);

        jMi_ConsultaComprobantes.setLabel("Consulta Comprobantes");
        jMi_ConsultaComprobantes.setName("jMi_ConsultaComprobantes");
        jMi_ConsultaComprobantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ConsultaComprobantesActionPerformed(evt);
            }
        });

        jMenu2.add(jMi_ConsultaComprobantes);

        jMenu2.add(jSeparator5);

        jMi_ConsultaCtaCte.setText("Consulta Cta.Cte.");
        jMi_ConsultaCtaCte.setName("jMi_ConsultaCtaCte");
        jMi_ConsultaCtaCte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ConsultaCtaCteActionPerformed(evt);
            }
        });

        jMenu2.add(jMi_ConsultaCtaCte);

        jMenu2.add(jSeparator8);

        jMi_AltaPagos.setText("Alta Pagos");
        jMi_AltaPagos.setName("jMi_AltaPagos");
        jMi_AltaPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_AltaPagosActionPerformed(evt);
            }
        });

        jMenu2.add(jMi_AltaPagos);

        jMi_ConsultaPagos.setText("Consulta de Pagos");
        jMi_ConsultaPagos.setName("jMi_ConsultaPagos");
        jMi_ConsultaPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ConsultaPagosActionPerformed(evt);
            }
        });

        jMenu2.add(jMi_ConsultaPagos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consulta");
        jMi_ConsultaConsorcio.setText("Consorcios");
        jMi_ConsultaConsorcio.setName("jMi_ConsultaConsorcio");
        jMi_ConsultaConsorcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ConsultaConsorcioActionPerformed(evt);
            }
        });

        jMenu3.add(jMi_ConsultaConsorcio);

        jMi_ConsultaUnidades.setText("Unidades");
        jMi_ConsultaUnidades.setName("jMi_ConsultaUnidades");
        jMi_ConsultaUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ConsultaUnidadesActionPerformed(evt);
            }
        });

        jMenu3.add(jMi_ConsultaUnidades);

        jMenu3.add(jSeparator6);

        jMi_ConsultaPropietario.setText("Propietario");
        jMi_ConsultaPropietario.setName("jMi_ConsultaPropietario");
        jMi_ConsultaPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ConsultaPropietarioActionPerformed(evt);
            }
        });

        jMenu3.add(jMi_ConsultaPropietario);

        jMi_ConsultaInquilinos.setText("Inquilinos");
        jMi_ConsultaInquilinos.setName("jMi_ConsultaInquilinos");
        jMi_ConsultaInquilinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ConsultaInquilinosActionPerformed(evt);
            }
        });

        jMenu3.add(jMi_ConsultaInquilinos);

        jMenu3.add(jSeparator7);

        jMi_ConsultaCoeficientes.setText("Coeficientes");
        jMi_ConsultaCoeficientes.setName("jMi_ConsultaCoeficientes");
        jMi_ConsultaCoeficientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ConsultaCoeficientesActionPerformed(evt);
            }
        });

        jMenu3.add(jMi_ConsultaCoeficientes);

        jMi_ConsultaConceptos.setText("Conceptos");
        jMi_ConsultaConceptos.setName("jMi_ConsultaConceptos");
        jMi_ConsultaConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ConsultaConceptosActionPerformed(evt);
            }
        });

        jMenu3.add(jMi_ConsultaConceptos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Liquidacion");
        jMi_ImprimirLiq.setText("Mostrar Liquidaciones");
        jMi_ImprimirLiq.setName("jMi_ImprimirLiq");
        jMi_ImprimirLiq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ImprimirLiqActionPerformed(evt);
            }
        });

        jMenu4.add(jMi_ImprimirLiq);

        jMi_GenerarLiq.setText("Generar Liquidaciones");
        jMi_GenerarLiq.setName("jMi_GenerarLiq");
        jMi_GenerarLiq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_GenerarLiqActionPerformed(evt);
            }
        });

        jMenu4.add(jMi_GenerarLiq);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Ing. Brutos");
        jMi_IngBrutos.setText("Liquidar Ing. Brutos");
        jMi_IngBrutos.setName("jMi_IngBrutos");
        jMi_IngBrutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_IngBrutosActionPerformed(evt);
            }
        });

        jMenu6.add(jMi_IngBrutos);

        jMenu6.add(jSeparator11);

        jMi_InformeAnexo.setText("Informe Anexo IG");
        jMi_InformeAnexo.setName("jMi_InformeAnexo");
        jMi_InformeAnexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_InformeAnexoActionPerformed(evt);
            }
        });

        jMenu6.add(jMi_InformeAnexo);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Listados");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        jMi_ListSaldo.setText("Listado de Saldos");
        jMi_ListSaldo.setName("jMi_ListSaldo");
        jMi_ListSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ListSaldoActionPerformed(evt);
            }
        });

        jMenu7.add(jMi_ListSaldo);

        jMi_ListExpComunes.setText("Listado de Expensas Comunes");
        jMi_ListExpComunes.setName("jMi_ListExpComunes");
        jMi_ListExpComunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ListExpComunesActionPerformed(evt);
            }
        });

        jMenu7.add(jMi_ListExpComunes);

        jMi_ListExpensas.setText("Listado de Expensas a Cobrar");
        jMi_ListExpensas.setName("jMi_ListExpensas");
        jMi_ListExpensas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ListExpensasActionPerformed(evt);
            }
        });

        jMenu7.add(jMi_ListExpensas);

        jMi_ListTotalConceptos.setText("Listado de Totales por Concepto");
        jMi_ListTotalConceptos.setName("jMi_ListTotalConceptos");
        jMi_ListTotalConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_ListTotalConceptosActionPerformed(evt);
            }
        });

        jMenu7.add(jMi_ListTotalConceptos);

        jMenuBar1.add(jMenu7);

        jMenu5.setText("Mantenimiento");
        jMi_Usuarios.setText("Usuarios");
        jMi_Usuarios.setName("jMi_Usuarios");
        jMi_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_UsuariosActionPerformed(evt);
            }
        });

        jMenu5.add(jMi_Usuarios);

        jMenu5.add(jSeparator10);

        jMi_BackupDB.setText("Backup DB");
        jMi_BackupDB.setName("jMi_BackupDB");
        jMi_BackupDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_BackupDBActionPerformed(evt);
            }
        });

        jMenu5.add(jMi_BackupDB);

        jMi_RestorDb.setText("Importar DB");
        jMi_RestorDb.setName("jMi_RestorDb");
        jMi_RestorDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_RestorDbActionPerformed(evt);
            }
        });

        jMenu5.add(jMi_RestorDb);

        jMenu5.add(jSeparator9);

        jMi_Propiedades.setText("Propiedades");
        jMi_Propiedades.setName("jMi_Propiedades");
        jMi_Propiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMi_PropiedadesActionPerformed(evt);
            }
        });

        jMenu5.add(jMi_Propiedades);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMi_ListTotalConceptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ListTotalConceptosActionPerformed
        ListadoTotalConceptos ltc=new ListadoTotalConceptos();
        Utilidades.centrarVentana(ltc);
        ltc.setVisible(true);
    }//GEN-LAST:event_jMi_ListTotalConceptosActionPerformed

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtn_SalirActionPerformed

    private void jBtn_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_UsuariosActionPerformed
        Usuarios us=new Usuarios();
        Utilidades.centrarVentana(us);
        us.setVisible(true);
    }//GEN-LAST:event_jBtn_UsuariosActionPerformed

    private void jBtn_IGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_IGActionPerformed
        ImpIngresosBrutos ig=new ImpIngresosBrutos();
        Utilidades.centrarVentana(ig);
        ig.setVisible(true);

    }//GEN-LAST:event_jBtn_IGActionPerformed

    private void jBtn_ConsultarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ConsultarPagosActionPerformed
        ConsultaPagos cp=new ConsultaPagos();
        SecurityManagerFwk sm=new SecurityManagerFwk();
        sm.validateSecurity(this.Usuario, cp);
        Utilidades.centrarVentana(cp);
        cp.setVisible(true);
    }//GEN-LAST:event_jBtn_ConsultarPagosActionPerformed

    private void jBtn_PagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_PagosActionPerformed
        AltaPagos ap=new AltaPagos();
        Utilidades.centrarVentana(ap);
        ap.setVisible(true);

    }//GEN-LAST:event_jBtn_PagosActionPerformed

    private void jBtn_CtaCteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CtaCteActionPerformed
        ConsultaCuentaCorriente ccc=new ConsultaCuentaCorriente();
        SecurityManagerFwk sm=new SecurityManagerFwk();
        sm.validateSecurity(this.Usuario, ccc);
        Utilidades.centrarVentana(ccc);
        ccc.setVisible(true);
    }//GEN-LAST:event_jBtn_CtaCteActionPerformed

    private void jBtn_MostrarLiquidacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_MostrarLiquidacionesActionPerformed
        ImpresionLiquidaciones il=new ImpresionLiquidaciones();
        Utilidades.centrarVentana(il);
        il.setVisible(true);

    }//GEN-LAST:event_jBtn_MostrarLiquidacionesActionPerformed

    private void jBtn_LiquidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_LiquidarActionPerformed
        LiquidarExpensas le=new LiquidarExpensas();
        Utilidades.centrarVentana(le);
        le.setVisible(true);
    }//GEN-LAST:event_jBtn_LiquidarActionPerformed

    private void jBtn_ConsultarComprobantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ConsultarComprobantesActionPerformed
        ConsultaGastosNoImp igni=new ConsultaGastosNoImp();
        SecurityManagerFwk sm=new SecurityManagerFwk();
        sm.validateSecurity(this.Usuario, igni);
        Utilidades.centrarVentana(igni);
        igni.setVisible(true);
    }//GEN-LAST:event_jBtn_ConsultarComprobantesActionPerformed

    private void jBtn_ComprobanteGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ComprobanteGastosActionPerformed
        ComprobantesGastos cg=new ComprobantesGastos();
        Utilidades.centrarVentana(cg);
        cg.setVisible(true);

    }//GEN-LAST:event_jBtn_ComprobanteGastosActionPerformed

    private void jMi_InformeAnexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_InformeAnexoActionPerformed
        InformeAnexoIGUI iai=new InformeAnexoIGUI();
        Utilidades.centrarVentana(iai);
        iai.setVisible(true);
    }//GEN-LAST:event_jMi_InformeAnexoActionPerformed

    private void jMi_ListExpensasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ListExpensasActionPerformed
        ListadoExpensasCobrar lec=new ListadoExpensasCobrar();
        Utilidades.centrarVentana(lec);
        lec.setVisible(true);
    }//GEN-LAST:event_jMi_ListExpensasActionPerformed

    private void jMi_ListExpComunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ListExpComunesActionPerformed
        ListadoExpensasComunes lec= new ListadoExpensasComunes();
        Utilidades.centrarVentana(lec);
        lec.setVisible(true);
    }//GEN-LAST:event_jMi_ListExpComunesActionPerformed

    private void jMi_ListSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ListSaldoActionPerformed
        ListadoSaldos ls=new ListadoSaldos();
        Utilidades.centrarVentana(ls);
        ls.setVisible(true);
    }//GEN-LAST:event_jMi_ListSaldoActionPerformed

    private void jMi_Numeros_ExpensasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_Numeros_ExpensasActionPerformed
        AdministrarNoExpensa ane = new AdministrarNoExpensa();
        Utilidades.centrarVentana(ane);
        ane.setVisible(true);
    }//GEN-LAST:event_jMi_Numeros_ExpensasActionPerformed

    private void jMi_PropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_PropiedadesActionPerformed
        AdministrarPropiedades ap=new AdministrarPropiedades();
        SecurityManagerFwk sm=new SecurityManagerFwk();
        sm.validateSecurity(this.Usuario, ap);
        Utilidades.centrarVentana(ap);
        ap.setVisible(true);
    }//GEN-LAST:event_jMi_PropiedadesActionPerformed

    private void jMi_ConsultaPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ConsultaPagosActionPerformed
        ConsultaPagos cp=new ConsultaPagos();
        SecurityManagerFwk sm=new SecurityManagerFwk();
        sm.validateSecurity(this.Usuario, cp);
        Utilidades.centrarVentana(cp);
        cp.setVisible(true);
        
    }//GEN-LAST:event_jMi_ConsultaPagosActionPerformed

    private void jMi_RestorDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_RestorDbActionPerformed
        ImportDB idb=new ImportDB();
        Utilidades.centrarVentana(idb);
        idb.setVisible(true);
    }//GEN-LAST:event_jMi_RestorDbActionPerformed

    private void jMi_BackupDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_BackupDBActionPerformed
        ExportDB exdb=new ExportDB();
        Utilidades.centrarVentana(exdb);
        exdb.setVisible(true);
    }//GEN-LAST:event_jMi_BackupDBActionPerformed

    private void jMi_ConsultaComprobantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ConsultaComprobantesActionPerformed
        ConsultaGastosNoImp igni=new ConsultaGastosNoImp();
        SecurityManagerFwk sm=new SecurityManagerFwk();
        sm.validateSecurity(this.Usuario, igni);
        Utilidades.centrarVentana(igni);
        igni.setVisible(true);
    }//GEN-LAST:event_jMi_ConsultaComprobantesActionPerformed

    private void jMi_IngBrutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_IngBrutosActionPerformed
        ImpIngresosBrutos ig=new ImpIngresosBrutos();
        Utilidades.centrarVentana(ig);
        ig.setVisible(true);
    }//GEN-LAST:event_jMi_IngBrutosActionPerformed

    private void jMi_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_UsuariosActionPerformed
        Usuarios us=new Usuarios();
        Utilidades.centrarVentana(us);
        us.setVisible(true);
    }//GEN-LAST:event_jMi_UsuariosActionPerformed

    private void jMi_ConsultaConceptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ConsultaConceptosActionPerformed
        ConsultaConcepto cc=new ConsultaConcepto();
        SecurityManagerFwk sm=new SecurityManagerFwk();
        sm.validateSecurity(this.Usuario, cc);
        Utilidades.centrarVentana(cc);
        cc.setVisible(true);
        
    }//GEN-LAST:event_jMi_ConsultaConceptosActionPerformed

    private void jMi_ConsultaCoeficientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ConsultaCoeficientesActionPerformed
        ConsultaCoeficientes cc=new ConsultaCoeficientes();
        SecurityManagerFwk sm=new SecurityManagerFwk();
        sm.validateSecurity(this.Usuario, cc);
        Utilidades.centrarVentana(cc);
        cc.setVisible(true);
    }//GEN-LAST:event_jMi_ConsultaCoeficientesActionPerformed

    private void jMi_ConsultaInquilinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ConsultaInquilinosActionPerformed
        ConsultaInquilino ci=new ConsultaInquilino();
        SecurityManagerFwk sm=new SecurityManagerFwk();
        sm.validateSecurity(this.Usuario, ci);
        Utilidades.centrarVentana(ci);
        ci.setVisible(true);
    }//GEN-LAST:event_jMi_ConsultaInquilinosActionPerformed

    private void jMi_ConsultaPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ConsultaPropietarioActionPerformed
        ConsultaPropietario cp=new ConsultaPropietario();
        SecurityManagerFwk sm=new SecurityManagerFwk();
        sm.validateSecurity(this.Usuario, cp);
        Utilidades.centrarVentana(cp);
        cp.setVisible(true);
    }//GEN-LAST:event_jMi_ConsultaPropietarioActionPerformed

    private void jMi_ConsultaUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ConsultaUnidadesActionPerformed
        ConsultaUnidad cu=new ConsultaUnidad();
        SecurityManagerFwk sm=new SecurityManagerFwk();
        sm.validateSecurity(this.Usuario, cu);
        Utilidades.centrarVentana(cu);
        cu.setVisible(true);
    }//GEN-LAST:event_jMi_ConsultaUnidadesActionPerformed

    private void jMi_ConsultaConsorcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ConsultaConsorcioActionPerformed
        ConsultaConsorcio cc=new ConsultaConsorcio();
        SecurityManagerFwk sm=new SecurityManagerFwk();
        sm.validateSecurity(this.Usuario, cc);
        Utilidades.centrarVentana(cc);
        cc.setVisible(true);
    }//GEN-LAST:event_jMi_ConsultaConsorcioActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
// TODO: Agrege su codigo aqui:
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMi_PropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_PropietarioActionPerformed
       AltaPropietarios ap=new AltaPropietarios();
       Utilidades.centrarVentana(ap);
       ap.setVisible(true);
    }//GEN-LAST:event_jMi_PropietarioActionPerformed

    private void jMi_GenerarLiqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_GenerarLiqActionPerformed
        LiquidarExpensas le=new LiquidarExpensas();
        Utilidades.centrarVentana(le);
        le.setVisible(true);
    }//GEN-LAST:event_jMi_GenerarLiqActionPerformed

    private void jMi_AltaComprobantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_AltaComprobantesActionPerformed
        ComprobantesGastos cg=new ComprobantesGastos();
        Utilidades.centrarVentana(cg);
        cg.setVisible(true);
    }//GEN-LAST:event_jMi_AltaComprobantesActionPerformed

    private void jMi_AsignarCoeficientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_AsignarCoeficientesActionPerformed
        AsignacionCoeficientes ac=new AsignacionCoeficientes();
        Utilidades.centrarVentana(ac);
        ac.setVisible(true);
    }//GEN-LAST:event_jMi_AsignarCoeficientesActionPerformed

    private void jMi_ImprimirLiqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ImprimirLiqActionPerformed
        ImpresionLiquidaciones il=new ImpresionLiquidaciones();
        Utilidades.centrarVentana(il);
        il.setVisible(true);
    }//GEN-LAST:event_jMi_ImprimirLiqActionPerformed

    private void jMi_ConsultaCtaCteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ConsultaCtaCteActionPerformed
        ConsultaCuentaCorriente ccc=new ConsultaCuentaCorriente();
        SecurityManagerFwk sm=new SecurityManagerFwk();
        sm.validateSecurity(this.Usuario, ccc);
        Utilidades.centrarVentana(ccc);
        ccc.setVisible(true);
    }//GEN-LAST:event_jMi_ConsultaCtaCteActionPerformed

    private void jMi_AltaPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_AltaPagosActionPerformed
        AltaPagos ap=new AltaPagos();
        Utilidades.centrarVentana(ap);
        ap.setVisible(true);
    }//GEN-LAST:event_jMi_AltaPagosActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMi_ConceptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ConceptosActionPerformed
        AltaConceptos acon=new AltaConceptos();
        Utilidades.centrarVentana(acon);
        acon.setVisible(true);
    }//GEN-LAST:event_jMi_ConceptosActionPerformed

    private void jMi_CoeficientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_CoeficientesActionPerformed
        AltaCoeficientes ac=new AltaCoeficientes();
        Utilidades.centrarVentana(ac);
        ac.setVisible(true);
    }//GEN-LAST:event_jMi_CoeficientesActionPerformed

    private void jMi_InquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_InquilinoActionPerformed
        AltaInquilinos ai=new AltaInquilinos();
        Utilidades.centrarVentana(ai);
        ai.setVisible(true);
    }//GEN-LAST:event_jMi_InquilinoActionPerformed

    private void jMi_UnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_UnidadesActionPerformed
        AltaUnidades au=new AltaUnidades();
        Utilidades.centrarVentana(au);
        au.setVisible(true);
    }//GEN-LAST:event_jMi_UnidadesActionPerformed

    private void jMi_ConsorcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMi_ConsorcioActionPerformed
        AltaConsorcio ac=new AltaConsorcio();
        Utilidades.centrarVentana(ac);
        ac.setVisible(true);
    }//GEN-LAST:event_jMi_ConsorcioActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    public User getUsuario() {
        return Usuario;
    }

    public void setUsuario(User Usuario) {
        this.Usuario = Usuario;
    }
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_ComprobanteGastos;
    private javax.swing.JButton jBtn_ConsultarComprobantes;
    private javax.swing.JButton jBtn_ConsultarPagos;
    private javax.swing.JButton jBtn_CtaCte;
    private javax.swing.JButton jBtn_IG;
    private javax.swing.JButton jBtn_Liquidar;
    private javax.swing.JButton jBtn_MostrarLiquidaciones;
    private javax.swing.JButton jBtn_Pagos;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JButton jBtn_Usuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMi_AltaComprobantes;
    private javax.swing.JMenuItem jMi_AltaPagos;
    private javax.swing.JMenuItem jMi_AsignarCoeficientes;
    private javax.swing.JMenuItem jMi_BackupDB;
    private javax.swing.JMenuItem jMi_Coeficientes;
    private javax.swing.JMenuItem jMi_Conceptos;
    private javax.swing.JMenuItem jMi_Consorcio;
    private javax.swing.JMenuItem jMi_ConsultaCoeficientes;
    private javax.swing.JMenuItem jMi_ConsultaComprobantes;
    private javax.swing.JMenuItem jMi_ConsultaConceptos;
    private javax.swing.JMenuItem jMi_ConsultaConsorcio;
    private javax.swing.JMenuItem jMi_ConsultaCtaCte;
    private javax.swing.JMenuItem jMi_ConsultaInquilinos;
    private javax.swing.JMenuItem jMi_ConsultaPagos;
    private javax.swing.JMenuItem jMi_ConsultaPropietario;
    private javax.swing.JMenuItem jMi_ConsultaUnidades;
    private javax.swing.JMenuItem jMi_GenerarLiq;
    private javax.swing.JMenuItem jMi_ImprimirLiq;
    private javax.swing.JMenuItem jMi_InformeAnexo;
    private javax.swing.JMenuItem jMi_IngBrutos;
    private javax.swing.JMenuItem jMi_Inquilino;
    private javax.swing.JMenuItem jMi_ListExpComunes;
    private javax.swing.JMenuItem jMi_ListExpensas;
    private javax.swing.JMenuItem jMi_ListSaldo;
    private javax.swing.JMenuItem jMi_ListTotalConceptos;
    private javax.swing.JMenuItem jMi_Numeros_Expensas;
    private javax.swing.JMenuItem jMi_Propiedades;
    private javax.swing.JMenuItem jMi_Propietario;
    private javax.swing.JMenuItem jMi_RestorDb;
    private javax.swing.JMenuItem jMi_Unidades;
    private javax.swing.JMenuItem jMi_Usuarios;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    // Fin de declaración de variables//GEN-END:variables
       public Map getObjectsAffected() {
        Map a=new HashMap();
        a.put(this.jMi_AltaComprobantes.getName(),this.jMi_AltaComprobantes);
        a.put(this.jMi_AltaPagos.getName(),this.jMi_AltaPagos);
        a.put(this.jMi_AsignarCoeficientes.getName(),this.jMi_AsignarCoeficientes);
        a.put(this.jMi_BackupDB.getName(),this.jMi_BackupDB);
        a.put(this.jMi_Coeficientes.getName(),this.jMi_Coeficientes);
        a.put(this.jMi_Conceptos.getName(),this.jMi_Conceptos);
        a.put(this.jMi_Consorcio.getName(),this.jMi_Consorcio);
        a.put(this.jMi_ConsultaCoeficientes.getName(),this.jMi_ConsultaCoeficientes);
        a.put(this.jMi_ConsultaComprobantes.getName(),this.jMi_ConsultaComprobantes);
        a.put(this.jMi_ConsultaConceptos.getName(),this.jMi_ConsultaConceptos);
        a.put(this.jMi_ConsultaConsorcio.getName(),this.jMi_ConsultaConsorcio);
        a.put(this.jMi_ConsultaCtaCte.getName(),this.jMi_ConsultaCtaCte);
        a.put(this.jMi_ConsultaInquilinos.getName(),this.jMi_ConsultaInquilinos);
        a.put(this.jMi_ConsultaPagos.getName(),this.jMi_ConsultaPagos);
        a.put(this.jMi_ConsultaPropietario.getName(),this.jMi_ConsultaPropietario);
        a.put(this.jMi_ConsultaUnidades.getName(),this.jMi_ConsultaUnidades);
        a.put(this.jMi_Unidades.getName(),this.jMi_Unidades);
        a.put(this.jMi_Propietario.getName(),this.jMi_Propietario);
        a.put(this.jMi_Inquilino.getName(),this.jMi_Inquilino);
        a.put(this.jMi_ImprimirLiq.getName(),this.jMi_ImprimirLiq);
        a.put(this.jMi_IngBrutos.getName(),this.jMi_IngBrutos);
        a.put(this.jMi_ListExpComunes.getName(),this.jMi_ListExpComunes);
        a.put(this.jMi_ListTotalConceptos.getName(),this.jMi_ListTotalConceptos);
        a.put(this.jMi_ListExpensas.getName(),this.jMi_ListExpensas);
        a.put(this.jMi_ListSaldo.getName(),this.jMi_ListSaldo);
        a.put(this.jMi_BackupDB.getName(),this.jMi_BackupDB);
        a.put(this.jMi_RestorDb.getName(),this.jMi_RestorDb);
        a.put(this.jMi_Usuarios.getName(),this.jMi_Usuarios);
        a.put(this.jMi_GenerarLiq.getName(),this.jMi_GenerarLiq);
        a.put(this.jMi_Propiedades.getName(),this.jMi_Propiedades);
        a.put(this.jMi_InformeAnexo.getName(),this.jMi_InformeAnexo);
        a.put(this.jMi_Numeros_Expensas.getName(),this.jMi_Numeros_Expensas);
        
        a.put(this.jBtn_ComprobanteGastos.getName(),this.jBtn_ComprobanteGastos);
        a.put(this.jBtn_ConsultarComprobantes.getName(),this.jBtn_ConsultarComprobantes);
        a.put(this.jBtn_Liquidar.getName(),this.jBtn_Liquidar);
        a.put(this.jBtn_MostrarLiquidaciones.getName(),this.jBtn_MostrarLiquidaciones);
        a.put(this.jBtn_CtaCte.getName(),this.jBtn_CtaCte);
        a.put(this.jBtn_Pagos.getName(),this.jBtn_Pagos);
        a.put(this.jBtn_ConsultarPagos.getName(),this.jBtn_ConsultarPagos);
        a.put(this.jBtn_IG.getName(),this.jBtn_IG);
        a.put(this.jBtn_Usuarios.getName(),this.jBtn_Usuarios);
        
        return a;
    }

    public String getUIName() {
        return "Menu";
    }
}
