/*
 * Usuarios.java
 *
 * Created on 26 de diciembre de 2007, 12:36
 */

package expensav20.GUI;

import Security.User;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

/**
 *
 * @author  Javier
 */
public class Usuarios extends javax.swing.JFrame {
    
    /** Creates new form Usuarios */
    public Usuarios() {
        initComponents();
        this.jTlb_Usuarios.setModel(new TableUsuariosModel());
        this.jTlb_Usuarios.updateUI();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTlb_Usuarios = new javax.swing.JTable();
        jBtn_Salir = new javax.swing.JButton();
        jBtn_Eliminar = new javax.swing.JButton();
        jBtn_Crear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administraci\u00f3n de Usuarios");
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Usuarios"));
        jTlb_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4"
            }
        ));
        jScrollPane1.setViewportView(jTlb_Usuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/door_out.png")));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });

        jBtn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/group_delete.png")));
        jBtn_Eliminar.setText("Eliminar");
        jBtn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EliminarActionPerformed(evt);
            }
        });

        jBtn_Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expensav20/GUI/Icons/group_add.png")));
        jBtn_Crear.setText("Crear");
        jBtn_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtn_Crear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Salir))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Salir)
                    .addComponent(jBtn_Eliminar)
                    .addComponent(jBtn_Crear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EliminarActionPerformed
        if (this.jTlb_Usuarios.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this.getContentPane(),"Debe seleccionar un usuario previamente");
            return;
        }
        User usr = (User)((TableUsuariosModel)this.jTlb_Usuarios.getModel()).getLst().get(this.jTlb_Usuarios.getSelectedRow());
        if (usr.getRole().getName().indexOf("Administrador")!=-1){
            int cantidad=usr.getCantidadAdministradores();
            if(cantidad==1){
                JOptionPane.showMessageDialog(this.getContentPane(),"No es posible eliminar el usuario dado que es el último administrador");
                return;
            }
        }
        if (JOptionPane.showConfirmDialog(this.getContentPane(),"Está seguro que desea eliminar al usuario?")==JOptionPane.YES_OPTION){
            if (usr.eliminar()){
                JOptionPane.showMessageDialog(this.getContentPane(),"El usuario fue eliminado correctamente");
            }
            else{
                JOptionPane.showMessageDialog(this.getContentPane(),"Ha ocurrido un problema, por favor intente nuevamente");
            }
        }
       this.refresh();

    }//GEN-LAST:event_jBtn_EliminarActionPerformed


    private void jBtn_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CrearActionPerformed
        UsuarioNuevo un=new UsuarioNuevo(this);
        un.setVisible(true);
    }//GEN-LAST:event_jBtn_CrearActionPerformed

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtn_SalirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Crear;
    private javax.swing.JButton jBtn_Eliminar;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTlb_Usuarios;
    // Fin de declaración de variables//GEN-END:variables
     class TableUsuariosModel implements TableModel{
        
        User usr= new User();
        protected Object selected;
        private List lst=new ArrayList();
         
        TableUsuariosModel(){
           lst=usr.buscarTodos();
        }
        
        public List getLst() {
            return lst;
        }

        public void setLst(List lst) {
            this.lst = lst;
        }

        public int getRowCount() {
            return this.getLst().size();
        }

        public int getColumnCount() {
            return 2;
        }

        public String getColumnName(int columnIndex) {
            switch (columnIndex){
                case 0: 
                    return "Usuario";
                case 1: 
                    return "Tipo Usuario";
            }
            return "";
        }
        public Class<?> getColumnClass(int columnIndex) {
            return this.getClass();
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
       

        public Object getValueAt(int rowIndex, int columnIndex) {
            switch(columnIndex){
                case 0:
                    return ((User)this.getLst().get(rowIndex)).getName();
                case 1:
                    return ((User)this.getLst().get(rowIndex)).getRole().getName();
            }
            
            return null;
        }
        

        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
        }

        public void addTableModelListener(TableModelListener l) {
        }

        public void removeTableModelListener(TableModelListener l) {
        }
    }
    public void refresh(){
        User usr=new User();
        ((TableUsuariosModel)this.jTlb_Usuarios.getModel()).setLst(usr.buscarTodos());
        this.jTlb_Usuarios.updateUI();
    }
   
}
